RTC::RTObject_impl Class Reference
RT-Component class.
#include <RTObject.h>
Classes
struct deactivate_comps
Functor to deactivate RTC.
struct ec_copy
Functor to copy ExecutionContext.
struct ec_find
Functor to find ExecutionContext.
struct nv_name
Functor to find NVList.
struct svc_name
Functor to find from SDOService Profile List by id.
Public Types
typedef PreComponentActionListener PreCompActionListener
Adding PreComponentAction type listener.
typedef PreComponentActionListenerType PreCompActionListenerType
typedef PostComponentActionListener PostCompActionListener
Adding PostComponentAction type listener.
typedef PostComponentActionListenerType PostCompActionListenerType
typedef ExecutionContextActionListenerType ECActionListenerType
Adding ExecutionContextAction type listener.
typedef ExecutionContextActionListener ECActionListener
Public Member Functions
RTObject_impl (Manager *manager)
Constructor.
RTObject_impl (CORBA::ORB_ptr orb, PortableServer::POA_ptr poa)
Constructor.
virtual ~RTObject_impl (void)
Virtual destructor.
virtual ReturnCode_t initialize () throw (CORBA::SystemException)
[CORBA interface] Initialize the RTC that realizes this interface.
virtual ReturnCode_t finalize () throw (CORBA::SystemException)
[CORBA interface] Finalize the RTC for destruction
virtual ReturnCode_t exit () throw (CORBA::SystemException)
[CORBA interface]top the RTC's execution context(s) and finalize it along with its contents.
virtual CORBA::Boolean is_alive (ExecutionContext_ptr exec_context) throw (CORBA::SystemException)
[CORBA interface] Confirm whether RTC is the alive state
virtual ExecutionContext_ptr get_context (UniqueId exec_handle) throw (CORBA::SystemException)
[CORBA interface] Get ExecutionContext.
virtual ExecutionContextList * get_owned_contexts () throw (CORBA::SystemException)
[CORBA interface] Get ExecutionContextList.
virtual ExecutionContextList * get_participating_contexts () throw (CORBA::SystemException)
[CORBA interface] Get participating ExecutionContextList.
virtual ExecutionContextHandle_t get_context_handle (ExecutionContext_ptr cxt) throw (CORBA::SystemException)
[CORBA interface] Return a handle of a ExecutionContext
UniqueId attach_context (ExecutionContext_ptr exec_context) throw (CORBA::SystemException)
[CORBA interface] Attach ExecutionContext
UniqueId bindContext (ExecutionContext_ptr exec_context)
ReturnCode_t detach_context (UniqueId exec_handle) throw (CORBA::SystemException)
[CORBA interface] Detach ExecutionContext.
virtual ComponentProfile * get_component_profile () throw (CORBA::SystemException)
[RTObject CORBA interface] Get RTC's profile
virtual PortServiceList * get_ports () throw (CORBA::SystemException)
[RTObject CORBA interface] Get Ports
virtual ReturnCode_t on_initialize () throw (CORBA::SystemException)
[RTObject CORBA interface] Get ExecutionContextAdmin
virtual ReturnCode_t on_finalize () throw (CORBA::SystemException)
[ComponentAction CORBA interface] Finalize RTC
virtual ReturnCode_t on_startup (UniqueId exec_handle) throw (CORBA::SystemException)
[ComponentAction CORBA interface] Startup RTC
virtual ReturnCode_t on_shutdown (UniqueId exec_handle) throw (CORBA::SystemException)
[ComponentAction CORBA interface] Shutdown RTC
virtual ReturnCode_t on_activated (UniqueId exec_handle) throw (CORBA::SystemException)
[ComponentAction CORBA interface] Activate RTC
virtual ReturnCode_t on_deactivated (UniqueId exec_handle) throw (CORBA::SystemException)
[ComponentAction CORBA interface] Deactivate RTC
virtual ReturnCode_t on_aborting (UniqueId exec_handle) throw (CORBA::SystemException)
[ComponentAction CORBA interface] Transition to Error State
virtual ReturnCode_t on_error (UniqueId exec_handle) throw (CORBA::SystemException)
[ComponentAction CORBA interface] Error Processing of RTC
virtual ReturnCode_t on_reset (UniqueId exec_handle) throw (CORBA::SystemException)
[ComponentAction CORBA interface] Resetting RTC
virtual ReturnCode_t on_execute (UniqueId exec_handle) throw (CORBA::SystemException)
[DataFlowComponentAction CORBA interface] Primary Periodic Operation of RTC
virtual ReturnCode_t on_state_update (UniqueId exec_handle) throw (CORBA::SystemException)
[DataFlowComponentAction CORBA interface] Secondary Periodic Operation of RTC
virtual ReturnCode_t on_rate_changed (UniqueId exec_handle) throw (CORBA::SystemException)
[DataFlowComponentAction CORBA interface] Notify rate changed
virtual SDOPackage::OrganizationList * get_owned_organizations () throw (CORBA::SystemException, SDOPackage::NotAvailable, SDOPackage::InternalError)
[SDO interface] Get Organization list
virtual char * get_sdo_id () throw (CORBA::SystemException,	     SDOPackage::NotAvailable, SDOPackage::InternalError)
[SDO interface] Get the SDO ID
virtual char * get_sdo_type () throw (CORBA::SystemException, 	     SDOPackage::NotAvailable, SDOPackage::InternalError)
[SDO interface] Get SDO type
virtual SDOPackage::DeviceProfile * get_device_profile () throw (CORBA::SystemException, 	     SDOPackage::NotAvailable, SDOPackage::InternalError)
[SDO interface] Get SDO DeviceProfile list
virtual SDOPackage::ServiceProfileList * get_service_profiles () throw (CORBA::SystemException, 	     SDOPackage::NotAvailable, SDOPackage::InternalError)
[SDO interface] Get SDO ServiceProfile
virtual SDOPackage::ServiceProfile * get_service_profile (const char *id) throw (CORBA::SystemException, 	     SDOPackage::InvalidParameter, SDOPackage::NotAvailable,	     SDOPackage::InternalError)
[SDO interface] Get specified ServiceProfile
virtual SDOPackage::SDOService_ptr get_sdo_service (const char *id) throw (CORBA::SystemException, 	     SDOPackage::InvalidParameter, SDOPackage::NotAvailable,	     SDOPackage::InternalError)
[SDO interface] Get specified SDO Service's reference
virtual SDOPackage::Configuration_ptr get_configuration () throw (CORBA::SystemException, 	     SDOPackage::InterfaceNotImplemented, SDOPackage::NotAvailable,	     SDOPackage::InternalError)
[SDO interface] Get Configuration object
virtual SDOPackage::Monitoring_ptr get_monitoring () throw (CORBA::SystemException, 	     SDOPackage::InterfaceNotImplemented, SDOPackage::NotAvailable,	     SDOPackage::InternalError)
[SDO interface] Get Monitoring object
virtual SDOPackage::OrganizationList * get_organizations () throw (CORBA::SystemException, 	     SDOPackage::NotAvailable, SDOPackage::InternalError)
[SDO interface] Get Organization list
virtual SDOPackage::NVList * get_status_list () throw (CORBA::SystemException, 	     SDOPackage::NotAvailable, SDOPackage::InternalError)
[SDO interface] Get SDO Status list
virtual CORBA::Any * get_status (const char *name) throw (CORBA::SystemException, 	     SDOPackage::InvalidParameter, SDOPackage::NotAvailable,	     SDOPackage::InternalError)
[SDO interface] Get SDO Status
const char * getInstanceName ()
[local interface] Get instance name
void setInstanceName (const char *instance_name)
[local interface] Set instance name
const char * getTypeName ()
[local interface] Get type name
const char * getDescription ()
[local interface] GetDescription
const char * getVersion ()
[local interface] Get version information
const char * getVendor ()
[local interface] Get vendor
const char * getCategory ()
[local interface] Get category information
std::vector< std::string > getNamingNames ()
[local interface] Get Naming Server information
void setObjRef (const RTObject_ptr rtobj)
[local interface] Set the object reference
RTObject_ptr getObjRef () const
[local interface] Get the object reference
void setProperties (const coil::Properties &prop)
[local interface] Set RTC property
coil::Properties & getProperties ()
[local interface] Get RTC property
template<typename VarType >
bool bindParameter (const char *param_name, VarType &var, const char *def_val, bool(*trans)(VarType &, const char *)=coil::stringTo)
Setup for configuration parameters.
void updateParameters (const char *config_set)
Update configuration parameters (by ID).
bool addPort (PortBase &port)
[local interface] Register Port
bool addPort (PortService_ptr port)
[local interface] Register Port
bool addPort (CorbaPort &port)
[local interface] Register Port
void registerPort (PortBase &port)
[local interface] Register Port
void registerPort (PortService_ptr port)
[local interface] Register Port
void registerPort (CorbaPort &port)
[local interface] Register Port
bool addInPort (const char *name, InPortBase &inport)
[local interface] Register DataInPort
void registerInPort (const char *name, InPortBase &inport)
[local interface] Register DataInPort
bool addOutPort (const char *name, OutPortBase &outport)
[local interface] Register DataOutPort
void registerOutPort (const char *name, OutPortBase &outport)
[local interface] Register DataOutPort
bool removeInPort (InPortBase &port)
[local interface] Unregister InPort
bool removeOutPort (OutPortBase &port)
[local interface] Unregister OutPort
bool removePort (PortBase &port)
[local interface] Unregister Port
bool removePort (PortService_ptr port)
[local interface] Unregister Port
bool removePort (CorbaPort &port)
[local interface] Unregister Port
void deletePort (PortBase &port)
[local interface] Unregister Port
void deletePort (PortService_ptr port)
[local interface] Unregister Port
void deletePort (CorbaPort &port)
[local interface] Unregister Port
void deletePortByName (const char *port_name)
[local interface] Delete Port by specifying its name
ExecutionContext_ptr getExecutionContext (RTC::UniqueId ec_id)
[local interface] Getting current execution context
double getExecutionRate (RTC::UniqueId ec_id)
[local interface] Getting current context' execution rate
ReturnCode_t setExecutionRate (RTC::UniqueId ec_id, double rate)
[local interface] Setting current context' execution rate
bool isOwnExecutionContext (RTC::UniqueId ec_id)
[local interface] Checking if the current context is own context
ReturnCode_t deactivate (RTC::UniqueId ec_id)
[local interface] Make transition to Inactive state
ReturnCode_t activate (RTC::UniqueId ec_id)
[local interface] Make transition to Active state
ReturnCode_t reset (RTC::UniqueId ec_id)
[local interface] Resetting and go to Inactive state
bool addSdoServiceProvider (const SDOPackage::ServiceProfile &prof, SdoServiceProviderBase *provider)
[local interface] Set a SDO service provider
bool removeSdoServiceProvider (const char *id)
[local interface] Remove a SDO service provider
bool addSdoServiceConsumer (const SDOPackage::ServiceProfile &prof)
[local interface] Set a SDO service provider
bool removeSdoServiceConsumer (const char *id)
[local interface] Remove a SDO service provider
bool readAll ()
Readout the value from All InPorts.
bool writeAll ()
The write() method of all OutPort is called.
void setReadAll (bool read=true, bool completion=false)
Set whether to execute the readAll() method.
void setWriteAll (bool write=true, bool completion=false)
Set whether to execute the writeAll() method.
void finalizePorts ()
Unregister All Ports.
void finalizeContexts ()
The ExecutionContextBase list is deleted.
void addPreComponentActionListener (PreComponentActionListenerType listener_type, PreComponentActionListener *listener, bool autoclean=true)
template<class Listener >
PreComponentActionListener * addPreComponentActionListener (PreCompActionListenerType listener_type, Listener &obj, void(Listener::*memfunc)(UniqueId ec_id))
void removePreComponentActionListener (PreComponentActionListenerType listener_type, PreComponentActionListener *listener)
Removing PreComponentAction type listener.
void addPostComponentActionListener (PostComponentActionListenerType listener_type, PostComponentActionListener *listener, bool autoclean=true)
template<class Listener >
PostComponentActionListener * addPostComponentActionListener (PostCompActionListenerType listener_type, Listener &obj, void(Listener::*memfunc)(UniqueId ec_id, ReturnCode_t ret))
void removePostComponentActionListener (PostComponentActionListenerType listener_type, PostComponentActionListener *listener)
Removing PostComponentAction type listener.
void addPortActionListener (PortActionListenerType listener_type, PortActionListener *listener, bool autoclean=true)
Adding PortAction type listener.
template<class Listener >
PortActionListener * addPortActionListener (PortActionListenerType listener_type, Listener &obj, void(Listener::*memfunc)(const RTC::PortProfile &))
void removePortActionListener (PortActionListenerType listener_type, PortActionListener *listener)
Removing PortAction type listener.
void addExecutionContextActionListener (ECActionListenerType listener_type, ECActionListener *listener, bool autoclean=true)
template<class Listener >
ECActionListener * addExecutionContextActionListener (ECActionListenerType listener_type, Listener &obj, void(Listener::*memfunc)(UniqueId))
void removeExecutionContextActionListener (ECActionListenerType listener_type, ECActionListener *listener)
Removing ExecutionContextAction type listener.
void addPortConnectListener (PortConnectListenerType listener_type, PortConnectListener *listener, bool autoclean=true)
Adding PortConnect type listener.
template<class Listener >
PortConnectListener * addPortConnectListener (PortConnectListenerType listener_type, Listener &obj, void(Listener::*memfunc)(const char *, ConnectorProfile &))
void removePortConnectListener (PortConnectListenerType listener_type, PortConnectListener *listener)
Removing PortConnect type listener.
void addPortConnectRetListener (PortConnectRetListenerType listener_type, PortConnectRetListener *listener, bool autoclean=true)
Adding PortConnectRet type listener.
template<class Listener >
PortConnectRetListener * addPortConnectRetListener (PortConnectRetListenerType listener_type, Listener &obj, void(Listener::*memfunc)(const char *, ConnectorProfile &, ReturnCode_t))
void removePortConnectRetListener (PortConnectRetListenerType listener_type, PortConnectRetListener *listener)
Removing PortConnectRet type listener.
void addConfigurationParamListener (ConfigurationParamListenerType type, ConfigurationParamListener *listener, bool autoclean=true)
Adding ConfigurationParamListener.
template<class Listener >
ConfigurationParamListener * addConfigurationParamListener (ConfigurationParamListenerType listener_type, Listener &obj, void(Listener::*memfunc)(const char *, const char *))
void removeConfigurationParamListener (ConfigurationParamListenerType type, ConfigurationParamListener *listener)
Removing ConfigurationParamListener.
void addConfigurationSetListener (ConfigurationSetListenerType type, ConfigurationSetListener *listener, bool autoclean=true)
Adding ConfigurationSetListener.
template<class Listener >
ConfigurationSetListener * addConfigurationSetListener (ConfigurationSetListenerType listener_type, Listener &obj, void(Listener::*memfunc)(const coil::Properties &config_set))
void removeConfigurationSetListener (ConfigurationSetListenerType type, ConfigurationSetListener *listener)
Removing ConfigurationSetListener.
void addConfigurationSetNameListener (ConfigurationSetNameListenerType type, ConfigurationSetNameListener *listener, bool autoclean=true)
Adding ConfigurationSetNameListener.
template<class Listener >
ConfigurationSetNameListener * addConfigurationSetNameListener (ConfigurationSetNameListenerType type, Listener &obj, void(Listener::*memfunc)(const char *))
void removeConfigurationSetNameListener (ConfigurationSetNameListenerType type, ConfigurationSetNameListener *listener)
Removing ConfigurationSetNameListener.
Protected Member Functions
virtual ReturnCode_t onInitialize ()
Callback function to initialize.
virtual ReturnCode_t onFinalize ()
Callback function to finalize.
virtual ReturnCode_t onStartup (RTC::UniqueId exec_handle)
Callback function for startup action.
virtual ReturnCode_t onShutdown (RTC::UniqueId exec_handle)
Callback function for shutdown action.
virtual ReturnCode_t onActivated (RTC::UniqueId exec_handle)
Callback function to activate.
virtual ReturnCode_t onDeactivated (RTC::UniqueId exec_handle)
Callback function to deactivate.
virtual ReturnCode_t onExecute (RTC::UniqueId exec_handle)
Callback function to execute periodically.
virtual ReturnCode_t onAborting (RTC::UniqueId exec_handle)
Callback function to abort.
virtual ReturnCode_t onError (RTC::UniqueId exec_handle)
Callback function for error handling.
virtual ReturnCode_t onReset (RTC::UniqueId exec_handle)
Callback function to reset.
virtual ReturnCode_t onStateUpdate (RTC::UniqueId exec_handle)
Callback function to update the state.
virtual ReturnCode_t onRateChanged (RTC::UniqueId exec_handle)
Callback function to change execution cycle.
void shutdown ()
Shutdown RTC.
void preOnInitialize (UniqueId ec_id)
void preOnFinalize (UniqueId ec_id)
void preOnStartup (UniqueId ec_id)
void preOnShutdown (UniqueId ec_id)
void preOnActivated (UniqueId ec_id)
void preOnDeactivated (UniqueId ec_id)
void preOnAborting (UniqueId ec_id)
void preOnError (UniqueId ec_id)
void preOnReset (UniqueId ec_id)
void preOnExecute (UniqueId ec_id)
void preOnStateUpdate (UniqueId ec_id)
void preOnRateChanged (UniqueId ec_id)
void postOnInitialize (UniqueId ec_id, ReturnCode_t ret)
void postOnFinalize (UniqueId ec_id, ReturnCode_t ret)
void postOnStartup (UniqueId ec_id, ReturnCode_t ret)
void postOnShutdown (UniqueId ec_id, ReturnCode_t ret)
void postOnActivated (UniqueId ec_id, ReturnCode_t ret)
void postOnDeactivated (UniqueId ec_id, ReturnCode_t ret)
void postOnAborting (UniqueId ec_id, ReturnCode_t ret)
void postOnError (UniqueId ec_id, ReturnCode_t ret)
void postOnReset (UniqueId ec_id, ReturnCode_t ret)
void postOnExecute (UniqueId ec_id, ReturnCode_t ret)
void postOnStateUpdate (UniqueId ec_id, ReturnCode_t ret)
void postOnRateChanged (UniqueId ec_id, ReturnCode_t ret)
void onAddPort (const PortProfile &pprof)
void onRemovePort (const PortProfile &pprof)
void onAttachExecutionContext (UniqueId ec_id)
void onDetachExecutionContext (UniqueId ec_id)
Protected Attributes
Logger rtclog
Logger stream.
Manager * m_pManager
Manager object.
CORBA::ORB_var m_pORB
The pointer to the ORB.
PortableServer::POA_var m_pPOA
The pointer to the POA.
SDOPackage::OrganizationList m_sdoOwnedOrganizations
SDO owned organization list.
SDOPackage::Configuration_impl * m_pSdoConfigImpl
The pointer to the SDO Configuration Object.
SDOPackage::Configuration_var m_pSdoConfig
The pointer to the SDO Configuration Interface.
SDOPackage::OrganizationList m_sdoOrganizations
SDO organization.
SDOPackage::NVList m_sdoStatus
SDO Status.
ComponentProfile m_profile
ComponentProfile.
RTObject_var m_objref
Object reference.
PortAdmin m_portAdmin
List of Port Object reference.
std::vector< InPortBase * > m_inports
List of InPortBase*.
std::vector< OutPortBase * > m_outports
List of OutPortBase*.
ExecutionContextServiceList m_ecMine
List of owned ExecutionContextService.
std::vector< ExecutionContextBase * > m_eclist
List of ExecutionContextBase.
ExecutionContextServiceList m_ecOther
List of participating ExecutionContextService.
bool m_created
Created Status Flag.
bool m_exiting
RTC Finalize Status Flag.
coil::Properties m_properties
Alive Status Flag.
ConfigAdmin m_configsets
Configuration Administrator Object.
SdoServiceAdmin m_sdoservice
SDO Service Administrator Object.
bool m_readAll
flag for readAll()
bool m_writeAll
flag for writeAll()
bool m_readAllCompletion
flag for readAll()
bool m_writeAllCompletion
flag for writeAll()
ComponentActionListeners m_actionListeners
ComponentActionListener holder.
PortConnectListeners m_portconnListeners
PortConnectListener holder.
Detailed Description
RT-Component class. This is a class to be a base of each RT-Component. This is a implementation class of lightweightRTComponent in Robotic Technology Component specification. This provides a implementation of ComponentAction interface that offers the the component's function and the implementation of LightweightRTObject for management of the component's lifecycle. When users actually create the components, they should use each subclass corresponding to Execution Semantics.
 (In current implementation, since only Periodic Sampled Data Processing is supported, this class inherits dataFlowComponent directly.)
Since
0.2.0
Member Typedef Documentation
typedef ExecutionContextActionListener RTC::RTObject_impl::ECActionListener
typedef ExecutionContextActionListenerType RTC::RTObject_impl::ECActionListenerType
Adding ExecutionContextAction type listener.
This operation adds certain listeners related to ComponentActions post events. The following listener types are available.
ADD_PORT: At adding ExecutionContext
REMOVE_PORT: At removing ExecutionContext
Listeners should have the following function operator().
ExecutionContextActionListener::operator()(UniqueId ec_id)
The ownership of the given listener object is transferred to this RTObject object in default. The given listener object will be destroied automatically in the RTObject's dtor or if the listener is deleted by removeExecutionContextActionListener() function. If you want to keep ownership of the listener object, give `false` value to 3rd argument to inhibit automatic destruction.
Parameters
listener_type A listener type
listener A pointer to a listener object
autoclean A flag for automatic listener destruction
typedef PostComponentActionListener RTC::RTObject_impl::PostCompActionListener
Adding PostComponentAction type listener.
This operation adds certain listeners related to ComponentActions post events. The following listener types are available.
POST_ON_INITIALIZE: after onInitialize
POST_ON_FINALIZE: after onFinalize
POST_ON_STARTUP: after onStartup
POST_ON_SHUTDOWN: after onShutdown
POST_ON_ACTIVATED: after onActivated
POST_ON_DEACTIVATED: after onDeactivated
POST_ON_ABORTED: after onAborted
POST_ON_ERROR: after onError
POST_ON_RESET: after onReset
POST_ON_EXECUTE: after onExecute
POST_ON_STATE_UPDATE: after onStateUpdate
Listeners should have the following function operator().
PostComponentActionListener::operator()(UniqueId ec_id, ReturnCode_t ret)
The ownership of the given listener object is transferred to this RTObject object in default. The given listener object will be destroied automatically in the RTObject's dtor or if the listener is deleted by removePostComponentActionListener() function. If you want to keep ownership of the listener object, give `false` value to 3rd argument to inhibit automatic destruction.
Parameters
listener_type A listener type
listener A pointer to a listener object
autoclean A flag for automatic listener destruction
typedef PostComponentActionListenerType RTC::RTObject_impl::PostCompActionListenerType
typedef PreComponentActionListener RTC::RTObject_impl::PreCompActionListener
Adding PreComponentAction type listener.
This operation adds certain listeners related to ComponentActions pre events. The following listener types are available.
PRE_ON_INITIALIZE: before onInitialize
PRE_ON_FINALIZE: before onFinalize
PRE_ON_STARTUP: before onStartup
PRE_ON_SHUTDOWN: before onShutdown
PRE_ON_ACTIVATED: before onActivated
PRE_ON_DEACTIVATED: before onDeactivated
PRE_ON_ABORTED: before onAborted
PRE_ON_ERROR: before onError
PRE_ON_RESET: before onReset
PRE_ON_EXECUTE: before onExecute
PRE_ON_STATE_UPDATE: before onStateUpdate
Listeners should have the following function operator().
PreComponentActionListener::operator()(UniqueId ec_id)
The ownership of the given listener object is transferred to this RTObject object in default. The given listener object will be destroied automatically in the RTObject's dtor or if the listener is deleted by removePreComponentActionListener() function. If you want to keep ownership of the listener object, give `false` value to 3rd argument to inhibit automatic destruction.
Parameters
listener_type A listener type
listener A pointer to a listener object
autoclean A flag for automatic listener destruction
typedef PreComponentActionListenerType RTC::RTObject_impl::PreCompActionListenerType
Constructor & Destructor Documentation
RTC::RTObject_impl::RTObject_impl (Manager * manager)
Constructor.
Constructor
Parameters
manager Manager object
RTC::RTObject_impl::RTObject_impl (CORBA::ORB_ptr orb, PortableServer::POA_ptr poa)
Constructor.
Constructor
Parameters
orb ORB
poa POA
virtual RTC::RTObject_impl::~RTObject_impl (void) [virtual]
Virtual destructor.
Member Function Documentation
ReturnCode_t RTC::RTObject_impl::activate (RTC::UniqueId ec_id)
[local interface] Make transition to Active state
This function makes transition from Inactive to Active state. This function is assumed to be called from the following functions.
onStartup()
onDeactivated()
The argument of this function should be the first argument (UniqueId ec_id) of the above function.
Parameters
ec_id The above functions' first argument `exec_handle.`
Returns
Return code
template<class Listener > ConfigurationParamListener* RTC::RTObject_impl::addConfigurationParamListener (ConfigurationParamListenerType listener_type, Listener & obj, void(Listener::*)(const char *, const char *) memfunc) [inline]
References addConfigurationParamListener().
void RTC::RTObject_impl::addConfigurationParamListener (ConfigurationParamListenerType type, ConfigurationParamListener * listener, bool autoclean = true)
Adding ConfigurationParamListener.
This function adds a listener object which is called when update(const char* config_set, const char* config_param) is called. In the type argument, currently only ON_UPDATE_CONFIG_PARAM is allowed.
Parameters
type ConfigurationParamListenerType value ON_UPDATE_CONFIG_PARAM is only allowed.
listener ConfigurationParamListener listener object.
autoclean a flag whether if the listener object autocleaned.
Referenced by addConfigurationParamListener().
template<class Listener > ConfigurationSetListener* RTC::RTObject_impl::addConfigurationSetListener (ConfigurationSetListenerType listener_type, Listener & obj, void(Listener::*)(const coil::Properties &config_set) memfunc) [inline]
References addConfigurationSetListener().
void RTC::RTObject_impl::addConfigurationSetListener (ConfigurationSetListenerType type, ConfigurationSetListener * listener, bool autoclean = true)
Adding ConfigurationSetListener.
This function add a listener object which is called when ConfigurationSet is updated. Available events are the followings.
Parameters
type ConfigurationSetListenerType value
listener ConfigurationSetListener listener object.
autoclean a flag whether if the listener object autocleaned.
Referenced by addConfigurationSetListener().
template<class Listener > ConfigurationSetNameListener* RTC::RTObject_impl::addConfigurationSetNameListener (ConfigurationSetNameListenerType type, Listener & obj, void(Listener::*)(const char *) memfunc) [inline]
References addConfigurationSetNameListener().
void RTC::RTObject_impl::addConfigurationSetNameListener (ConfigurationSetNameListenerType type, ConfigurationSetNameListener * listener, bool autoclean = true)
Adding ConfigurationSetNameListener.
This function add a listener object which is called when ConfigurationSetName is updated. Available events are the followings.
ON_UPDATE_CONFIG_SET: A ConfigurationSet has been updated.
ON_REMOVE_CONFIG_SET: A ConfigurationSet has been deleted.
ON_ACTIVATE_CONFIG_SET: A ConfigurationSet has been activated.
Parameters
type ConfigurationSetNameListenerType value
listener ConfigurationSetNameListener listener object.
autoclean a flag whether if the listener object autocleaned.
Referenced by addConfigurationSetNameListener().
template<class Listener > ECActionListener* RTC::RTObject_impl::addExecutionContextActionListener (ECActionListenerType listener_type, Listener & obj, void(Listener::*)(UniqueId) memfunc) [inline]
References addExecutionContextActionListener().
void RTC::RTObject_impl::addExecutionContextActionListener (ECActionListenerType listener_type, ECActionListener * listener, bool autoclean = true)
Referenced by addExecutionContextActionListener().
bool RTC::RTObject_impl::addInPort (const char * name, InPortBase & inport)
[local interface] Register DataInPort
This operation registers DataInPort held by this RTC. Set `port.dataport` and `tcp_any` to property of Port, and create instances of DataInPort and register it.
Parameters
name Port name
inport DataInPort which is registered to the RTC
Returns
Register result (Successful:true, Failed:false)
bool RTC::RTObject_impl::addOutPort (const char * name, OutPortBase & outport)
[local interface] Register DataOutPort
This operation registers DataOutPor held by this RTC. Set `port.dataport` and `tcp_any` to property of Port, and then create instances of DataOutPort and register it.
Parameters
name Port name
outport DataOutPort which is registered to the RTC
Returns
Register result (Successful:true, Failed:false)
bool RTC::RTObject_impl::addPort (CorbaPort & port)
[local interface] Register Port
This operation registers a Port held by this RTC. In order to enable access to the Port from outside of RTC, the Port must be registered by this operation. The Port that is registered by this operation would be identified by PortProfile.name in the inside of RTC. Therefore, the Port should have unique PortProfile.name in the RTC. The registering Port would be activated properly, and the reference and the object reference would be stored in lists in RTC.
Parameters
port Port which is registered to the RTC
Returns
Register result (Successful:true, Failed:false)
bool RTC::RTObject_impl::addPort (PortService_ptr port)
[local interface] Register Port
This operation registers a Port held by this RTC. In order to enable access to the Port from outside of RTC, the Port must be registered by this operation. The Port that is registered by this operation would be identified by PortProfile.name in the inside of RTC. Therefore, the Port should have unique PortProfile.name in the RTC. The registering Port would be activated properly, and the reference and the object reference would be stored in lists in RTC.
Parameters
port Port which is registered to the RTC
Returns
Register result (Successful:true, Failed:false)
bool RTC::RTObject_impl::addPort (PortBase & port)
[local interface] Register Port
This operation registers a Port held by this RTC. In order to enable access to the Port from outside of RTC, the Port must be registered by this operation. The Port that is registered by this operation would be identified by PortProfile.name in the inside of RTC. Therefore, the Port should have unique PortProfile.name in the RTC. The registering Port would be activated properly, and the reference and the object reference would be stored in lists in RTC.
Parameters
port Port which is registered to the RTC
Returns
Register result (Successful:true, Failed:false)
template<class Listener > PortActionListener* RTC::RTObject_impl::addPortActionListener (PortActionListenerType listener_type, Listener & obj, void(Listener::*)(const RTC::PortProfile &) memfunc) [inline]
References addPortActionListener().
void RTC::RTObject_impl::addPortActionListener (PortActionListenerType listener_type, PortActionListener * listener, bool autoclean = true)
Adding PortAction type listener.
This operation adds certain listeners related to ComponentActions post events. The following listener types are available.
ADD_PORT: At adding Port
REMOVE_PORT: At removing Port
Listeners should have the following function operator().
PortActionListener::operator()(RTC::PortProfile pprof)
The ownership of the given listener object is transferred to this RTObject object in default. The given listener object will be destroied automatically in the RTObject's dtor or if the listener is deleted by removePortActionListener() function. If you want to keep ownership of the listener object, give `false` value to 3rd argument to inhibit automatic destruction.
Parameters
listener_type A listener type
listener A pointer to a listener object
autoclean A flag for automatic listener destruction
Referenced by addPortActionListener().
template<class Listener > PortConnectListener* RTC::RTObject_impl::addPortConnectListener (PortConnectListenerType listener_type, Listener & obj, void(Listener::*)(const char *, ConnectorProfile &) memfunc) [inline]
References addPortConnectListener().
void RTC::RTObject_impl::addPortConnectListener (PortConnectListenerType listener_type, PortConnectListener * listener, bool autoclean = true)
Adding PortConnect type listener.
This operation adds certain listeners related to Port's connect actions. The following listener types are available.
ON_NOTIFY_CONNECT: right after entering into notify_connect()
ON_NOTIFY_DISCONNECT: right after entering into notify_disconnect()
ON_UNSUBSCRIBE_INTERFACES: unsubscribing IF in notify_disconnect()
Listeners should have the following function operator().
PortConnectListener::operator()(const char*, ConnectorProfile)
The ownership of the given listener object is transferred to this RTObject object in default. The given listener object will be destroied automatically in the RTObject's dtor or if the listener is deleted by removePortConnectListener() function. If you want to keep ownership of the listener object, give `false` value to 3rd argument to inhibit automatic destruction.
Parameters
listener_type A listener type
listener A pointer to a listener object
autoclean A flag for automatic listener destruction
Referenced by addPortConnectListener().
template<class Listener > PortConnectRetListener* RTC::RTObject_impl::addPortConnectRetListener (PortConnectRetListenerType listener_type, Listener & obj, void(Listener::*)(const char *, ConnectorProfile &, ReturnCode_t) memfunc) [inline]
References addPortConnectRetListener().
void RTC::RTObject_impl::addPortConnectRetListener (PortConnectRetListenerType listener_type, PortConnectRetListener * listener, bool autoclean = true)
Adding PortConnectRet type listener.
This operation adds certain listeners related to Port's connect actions. The following listener types are available.
ON_CONNECT_NEXTPORT: after cascade-call in notify_connect()
ON_SUBSCRIBE_INTERFACES: after IF subscribing in notify_connect()
ON_CONNECTED: completed nofity_connect() connection process
ON_DISCONNECT_NEXT: after cascade-call in notify_disconnect()
ON_DISCONNECTED: completed notify_disconnect() disconnection process
Listeners should have the following function operator().
PortConnectRetListener::operator()(const char*, ConnectorProfile)
The ownership of the given listener object is transferred to this RTObject object in default. The given listener object will be destroied automatically in the RTObject's dtor or if the listener is deleted by removePortConnectRetListener() function. If you want to keep ownership of the listener object, give `false` value to 3rd argument to inhibit automatic destruction.
Parameters
listener_type A listener type
listener A pointer to a listener object
autoclean A flag for automatic listener destruction
Referenced by addPortConnectRetListener().
template<class Listener > PostComponentActionListener* RTC::RTObject_impl::addPostComponentActionListener (PostCompActionListenerType listener_type, Listener & obj, void(Listener::*)(UniqueId ec_id, ReturnCode_t ret) memfunc) [inline]
References addPostComponentActionListener().
void RTC::RTObject_impl::addPostComponentActionListener (PostComponentActionListenerType listener_type, PostComponentActionListener * listener, bool autoclean = true)
Referenced by addPostComponentActionListener().
template<class Listener > PreComponentActionListener* RTC::RTObject_impl::addPreComponentActionListener (PreCompActionListenerType listener_type, Listener & obj, void(Listener::*)(UniqueId ec_id) memfunc) [inline]
References addPreComponentActionListener().
void RTC::RTObject_impl::addPreComponentActionListener (PreComponentActionListenerType listener_type, PreComponentActionListener * listener, bool autoclean = true)
Referenced by addPreComponentActionListener().
bool RTC::RTObject_impl::addSdoServiceConsumer (const SDOPackage::ServiceProfile & prof)
[local interface] Set a SDO service provider
bool RTC::RTObject_impl::addSdoServiceProvider (const SDOPackage::ServiceProfile & prof, SdoServiceProviderBase * provider)
[local interface] Set a SDO service provider
UniqueId RTC::RTObject_impl::attach_context (ExecutionContext_ptr exec_context) throw (CORBA::SystemException)
[CORBA interface] Attach ExecutionContext
Inform this RTC that it is participating in the given execution context. Return a handle that represents the association of this RTC with the context. This operation is intended to be invoked by ExecutionContextOperations::add_component. It is not intended for use by other clients.
Parameters
exec_context Participating ExecutionContext
Returns
ExecutionContext Handle
UniqueId RTC::RTObject_impl::bindContext (ExecutionContext_ptr exec_context)
template<typename VarType > bool RTC::RTObject_impl::bindParameter (const char * param_name, VarType & var, const char * def_val, bool(*)(VarType &, const char *) trans = coil::stringTo) [inline]
Setup for configuration parameters.
Bind configuration parameter to its variable. Specify the data type of configuration parameter as <VarType>.
Parameters
param_name Configuration parameter name
var Variables to store configuration parameter
def_val Default value of configuration parameter
trans Function to transform configuration parameter type into string format
Returns
Setup result (Successful:true, Failed:false)
References RTC::ConfigAdmin::bindParameter(), m_configsets, and RTC_TRACE.
ReturnCode_t RTC::RTObject_impl::deactivate (RTC::UniqueId ec_id)
[local interface] Make transition to Inactive state
This function makes transition from Active to Inactive state. This function is assumed to be called from the following functions.
onActivated()
onExecute()
onStateUpdate()
The argument of this function should be the first argument (UniqueId ec_id) of the above function.
Parameters
ec_id The above functions' first argument `exec_handle.`
Returns
Return code
void RTC::RTObject_impl::deletePort (CorbaPort & port)
[local interface] Unregister Port
This operation unregisters a Port held by this RTC.
Parameters
port Port which is unregistered
void RTC::RTObject_impl::deletePort (PortService_ptr port)
[local interface] Unregister Port
This operation unregisters a Port held by this RTC.
Parameters
port Port which is unregistered
void RTC::RTObject_impl::deletePort (PortBase & port)
[local interface] Unregister Port
This operation unregisters a Port held by this RTC.
Parameters
port Port which is unregistered
void RTC::RTObject_impl::deletePortByName (const char * port_name)
[local interface] Delete Port by specifying its name
Delete Port which RTC has by specifying its name.
Parameters
port_name Name of Port which is deleted
ReturnCode_t RTC::RTObject_impl::detach_context (UniqueId exec_handle) throw (CORBA::SystemException)
[CORBA interface] Detach ExecutionContext.
Inform this RTC that it is no longer participating in the given execution context. This operation is intended to be invoked by ExecutionContextOperations::remove. It is not intended for use by other clients. Constraints
This operation may not be invoked if this RTC is not already participating in the execution context. Such a call shall fail with ReturnCode_t::PRECONDITION_NOT_MET.
This operation may not be invoked if this RTC is Active in the indicated execution context. Otherwise, it shall fail with ReturnCode_t::PRECONDITION_NOT_MET.
Parameters
exec_handle Detaching ExecutionContext Handle
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::exit () throw (CORBA::SystemException) [virtual]
[CORBA interface]top the RTC's execution context(s) and finalize it along with its contents.
Any execution contexts for which the RTC is the owner shall be stopped. If the RTC participates in any execution contexts belonging to another RTC that contains it, directly or indirectly (i.e. the containing RTC is the owner of the ExecutionContext), it shall be deactivated in those contexts. After the RTC is no longer Active in any Running execution context, it and any RTCs contained transitively within it shall be finalized.
Constraints
An RTC cannot be exited if it has not yet been initialized. Any attempt to exit an RTC that is in the Created state shall fail with ReturnCode_t::PRECONDITION_NOT_MET.
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::finalize () throw (CORBA::SystemException) [virtual]
[CORBA interface] Finalize the RTC for destruction
This invocation of this operation shall result in the invocation of the callback ComponentAction::on_finalize.
Constraints
An RTC may not be finalized while it is participating in any execution context. It must first be removed with ExecutionContextOperations::remove. Otherwise, this operation shall fail with ReturnCode_t::PRECONDITION_NOT_MET.
An RTC may not be finalized while it is in the Created state. Any attempt to invoke this operation while in that state shall fail with ReturnCode_t::PRECONDITION_NOT_MET.
Application developers are not expected to call this operation directly; it exists for use by the RTC infrastructure.
Returns
The return code of ReturnCode_t type
void RTC::RTObject_impl::finalizeContexts ()
The ExecutionContextBase list is deleted.
void RTC::RTObject_impl::finalizePorts ()
Unregister All Ports.
This operation deactivates the all Ports and deletes the all Port's registrations in the RTC
virtual ComponentProfile* RTC::RTObject_impl::get_component_profile () throw (CORBA::SystemException) [virtual]
[RTObject CORBA interface] Get RTC's profile
This operation returns the ComponentProfile of the RTC.
Returns
ComponentProfile
virtual SDOPackage::Configuration_ptr RTC::RTObject_impl::get_configuration () throw (CORBA::SystemException, 	     SDOPackage::InterfaceNotImplemented, SDOPackage::NotAvailable,	     SDOPackage::InternalError) [virtual]
[SDO interface] Get Configuration object
This operation returns an object implementing the Configuration interface. The Configuration interface is one of the interfaces that each SDO maintains. The interface is used to configure the attributes defined in DeviceProfile, ServiceProfile, and Organization. See OMG SDO specification Section 2.3.5, `Configuration Interface,` on page 2-24 for more details about the Configuration interface.
Returns
The Configuration interface of an SDO.
Exceptions
InterfaceNotImplemented The target SDO has no Configuration interface.
SDONotExists The target SDO does not exist.(This exception is mapped to CORBA standard system exception OBJECT_NOT_EXIST.)
NotAvailable The target SDO is reachable but cannot respond.
InternalError The target SDO cannot execute the operation completely due to some internal error.
virtual ExecutionContext_ptr RTC::RTObject_impl::get_context (UniqueId exec_handle) throw (CORBA::SystemException) [virtual]
[CORBA interface] Get ExecutionContext.
Obtain a reference to the execution context represented by the given handle. The mapping from handle to context is specific to a particular RTC instance. The given handle must have been obtained by a previous call to attach_context on this RTC.
Parameters
exec_handle ExecutionContext handle
Returns
ExecutionContext
virtual ExecutionContextHandle_t RTC::RTObject_impl::get_context_handle (ExecutionContext_ptr cxt) throw (CORBA::SystemException) [virtual]
[CORBA interface] Return a handle of a ExecutionContext
This operation returns a handle that is associated with the given execution context.
virtual SDOPackage::DeviceProfile* RTC::RTObject_impl::get_device_profile () throw (CORBA::SystemException, 	     SDOPackage::NotAvailable, SDOPackage::InternalError) [virtual]
[SDO interface] Get SDO DeviceProfile list
This operation returns the DeviceProfile of the SDO. If the SDO does not represent any hardware device, then a DeviceProfile with empty values are returned. This operation throws SDOException with one of the following types.
Returns
The DeviceProfile of the SDO.
Exceptions
SDONotExists The target SDO does not exist.(This exception is mapped to CORBA standard system exception OBJECT_NOT_EXIST.)
NotAvailable The target SDO is reachable but cannot respond.
InternalError The target SDO cannot execute the operation completely due to some internal error.
virtual SDOPackage::Monitoring_ptr RTC::RTObject_impl::get_monitoring () throw (CORBA::SystemException, 	     SDOPackage::InterfaceNotImplemented, SDOPackage::NotAvailable,	     SDOPackage::InternalError) [virtual]
[SDO interface] Get Monitoring object
This operation returns an object implementing the Monitoring interface. The Monitoring interface is one of the interfaces that each SDO maintains. The interface is used to monitor the properties of an SDO. See OMG SDO specification Section 2.3.7, `Monitoring Interface,` on page 2-35 for more details about the Monitoring interface.
Returns
The Monitoring interface of an SDO.
Exceptions
InterfaceNotImplemented The target SDO has no Configuration interface.
SDONotExists The target SDO does not exist.(This exception is mapped to CORBA standard system exception OBJECT_NOT_EXIST.)
NotAvailable The target SDO is reachable but cannot respond.
InternalError The target SDO cannot execute the operation completely due to some internal error.
virtual SDOPackage::OrganizationList* RTC::RTObject_impl::get_organizations () throw (CORBA::SystemException, 	     SDOPackage::NotAvailable, SDOPackage::InternalError) [virtual]
[SDO interface] Get Organization list
An SDO belongs to zero or more organizations. If the SDO belongs to one or more organizations, this operation returns the list of organizations that the SDO belongs to. An empty list is returned if the SDO does not belong to any Organizations.
Returns
The list of Organizations that the SDO belong to.
Exceptions
SDONotExists The target SDO does not exist.(This exception is mapped to CORBA standard system exception OBJECT_NOT_EXIST.)
NotAvailable The target SDO is reachable but cannot respond.
InternalError The target SDO cannot execute the operation completely due to some internal error.
virtual ExecutionContextList* RTC::RTObject_impl::get_owned_contexts () throw (CORBA::SystemException) [virtual]
[CORBA interface] Get ExecutionContextList.
This operation returns a list of all execution contexts owned by this RTC.
Returns
ExecutionContext List
virtual SDOPackage::OrganizationList* RTC::RTObject_impl::get_owned_organizations () throw (CORBA::SystemException, SDOPackage::NotAvailable, SDOPackage::InternalError) [virtual]
[SDO interface] Get Organization list
SDOSystemElement can be the owner of zero or more organizations. If the SDOSystemElement owns one or more Organizations, this operation returns the list of Organizations that the SDOSystemElement owns. If it does not own any Organization, it returns empty list.
Returns
Owned Organization List
Exceptions
SDONotExists The target SDO does not exist.(This exception is mapped to CORBA standard system exception OBJECT_NOT_EXIST.)
NotAvailable The target SDO is reachable but cannot respond.
InternalError The target SDO cannot execute the operation completely due to some internal error.
virtual ExecutionContextList* RTC::RTObject_impl::get_participating_contexts () throw (CORBA::SystemException) [virtual]
[CORBA interface] Get participating ExecutionContextList.
This operation returns a list of all execution contexts in which this RTC participates.
Returns
ExecutionContext List
virtual PortServiceList* RTC::RTObject_impl::get_ports () throw (CORBA::SystemException) [virtual]
[RTObject CORBA interface] Get Ports
This operation returns the reference of ports held by RTC.
Returns
PortServiceList
virtual char* RTC::RTObject_impl::get_sdo_id () throw (CORBA::SystemException,	     SDOPackage::NotAvailable, SDOPackage::InternalError) [virtual]
[SDO interface] Get the SDO ID
This operation returns id of the SDO. This operation throws SDOException with one of the following types.
Returns
id of the SDO defined in the resource data model.
Exceptions
SDONotExists The target SDO does not exist.(This exception is mapped to CORBA standard system exception OBJECT_NOT_EXIST.)
NotAvailable The target SDO is reachable but cannot respond.
InternalError The target SDO cannot execute the operation completely due to some internal error.
virtual SDOPackage::SDOService_ptr RTC::RTObject_impl::get_sdo_service (const char * id) throw (CORBA::SystemException, 	     SDOPackage::InvalidParameter, SDOPackage::NotAvailable,	     SDOPackage::InternalError) [virtual]
[SDO interface] Get specified SDO Service's reference
This operation returns an object implementing an SDO's service that is identified by the identifier specified as an argument. Different services provided by an SDO are distinguished with different identifiers. See OMG SDO specification Section 2.2.8, `ServiceProfile,` on page 2-12 for more details.
Parameters
id The identifier referring to one of the SDO Service
Returns
The reference requested to SDO Service.
Exceptions
InvalidParameter Argument id is null, or if the ServiceProfile that is specified by argument id does not exist.
SDONotExists The target SDO does not exist.(This exception is mapped to CORBA standard system exception OBJECT_NOT_EXIST.)
NotAvailable The target SDO is reachable but cannot respond.
InternalError The target SDO cannot execute the operation completely due to some internal error.
virtual char* RTC::RTObject_impl::get_sdo_type () throw (CORBA::SystemException, 	     SDOPackage::NotAvailable, SDOPackage::InternalError) [virtual]
[SDO interface] Get SDO type
This operation returns sdoType of the SDO. This operation throws SDOException with one of the following types.
Returns
Type of the SDO defined in the resource data model.
Exceptions
SDONotExists The target SDO does not exist.(This exception is mapped to CORBA standard system exception OBJECT_NOT_EXIST.)
NotAvailable The target SDO is reachable but cannot respond.
InternalError The target SDO cannot execute the operation completely due to some internal error.
virtual SDOPackage::ServiceProfile* RTC::RTObject_impl::get_service_profile (const char * id) throw (CORBA::SystemException, 	     SDOPackage::InvalidParameter, SDOPackage::NotAvailable,	     SDOPackage::InternalError) [virtual]
[SDO interface] Get specified ServiceProfile
This operation returns the ServiceProfile that is specified by the argument `id.`
Parameters
id The identifier referring to one of the ServiceProfiles.
Returns
The profile of the specified service.
Exceptions
InvalidParameter The ServiceProfile that is specified by the argument 'id' does not exist or if 'id' is 'null.'
SDONotExists The target SDO does not exist.(This exception is mapped to CORBA standard system exception OBJECT_NOT_EXIST.)
NotAvailable The target SDO is reachable but cannot respond.
InternalError The target SDO cannot execute the operation completely due to some internal error.
virtual SDOPackage::ServiceProfileList* RTC::RTObject_impl::get_service_profiles () throw (CORBA::SystemException, 	     SDOPackage::NotAvailable, SDOPackage::InternalError) [virtual]
[SDO interface] Get SDO ServiceProfile
This operation returns a list of ServiceProfiles that the SDO has. If the SDO does not provide any service, then an empty list is returned. This operation throws SDOException with one of the following types.
Returns
List of ServiceProfiles of all the services the SDO is providing.
Exceptions
SDONotExists The target SDO does not exist.(This exception is mapped to CORBA standard system exception OBJECT_NOT_EXIST.)
NotAvailable The target SDO is reachable but cannot respond.
InternalError The target SDO cannot execute the operation completely due to some internal error.
virtual CORBA::Any* RTC::RTObject_impl::get_status (const char * name) throw (CORBA::SystemException, 	     SDOPackage::InvalidParameter, SDOPackage::NotAvailable,	     SDOPackage::InternalError) [virtual]
[SDO interface] Get SDO Status
Parameters
name One of the parameters defining the `status` of an SDO.
Returns
The value of the specified status parameter.
Exceptions
SDONotExists The target SDO does not exist.(This exception is mapped to CORBA standard system exception OBJECT_NOT_EXIST.)
NotAvailable The target SDO is reachable but cannot respond.
InvalidParameter The parameter defined by `name` is null or does not exist.
InternalError The target SDO cannot execute the operation completely due to some internal error.
virtual SDOPackage::NVList* RTC::RTObject_impl::get_status_list () throw (CORBA::SystemException, 	     SDOPackage::NotAvailable, SDOPackage::InternalError) [virtual]
[SDO interface] Get SDO Status list
This operation returns an NVlist describing the status of an SDO.
Returns
The actual status of an SDO.
Exceptions
SDONotExists The target SDO does not exist.(This exception is mapped to CORBA standard system exception OBJECT_NOT_EXIST.)
NotAvailable The target SDO is reachable but cannot respond.
InternalError The target SDO cannot execute the operation completely due to some internal error.
const char* RTC::RTObject_impl::getCategory () [inline]
[local interface] Get category information
Get the category information that has been set in ComponentProfile.
Returns
Category information
References m_profile, and RTC_TRACE.
const char* RTC::RTObject_impl::getDescription () [inline]
[local interface] GetDescription
Get the Description has been set in ComponentProfile.
Returns
Description
References m_profile, and RTC_TRACE.
ExecutionContext_ptr RTC::RTObject_impl::getExecutionContext (RTC::UniqueId ec_id)
[local interface] Getting current execution context
This function is the local version of get_context(). completely same as get_context() function. This function is assumed to be called from the following functions.
onStartup()
onShutdown()
onActivated()
onDeactivated()
onExecute()
onAborting()
onError()
onReset()
onStateUpdate()
onRateChanged()
The argument of this function should be the first argument (UniqueId ec_id) of the above functions.
Parameters
ec_id The above functions' first argument `exec_handle.`
double RTC::RTObject_impl::getExecutionRate (RTC::UniqueId ec_id)
[local interface] Getting current context' execution rate
This function returns current execution rate in this context. If this context's kind is not PERIODC, behavior is not defined. This function is assumed to be called from the following functions.
onStartup()
onShutdown()
onActivated()
onDeactivated()
onExecute()
onAborting()
onError()
onReset()
onStateUpdate()
onRateChanged()
The argument of this function should be the first argument (UniqueId ec_id) of the above functions.
Parameters
ec_id The above functions' first argument `exec_handle.`
const char* RTC::RTObject_impl::getInstanceName () [inline]
[local interface] Get instance name
Return the instance name that has been set in ComponentProfile.
Returns
Instance name
References m_profile, and RTC_TRACE.
std::vector<std::string> RTC::RTObject_impl::getNamingNames ()
[local interface] Get Naming Server information
Get Naming Server information that has been set.
Returns
Naming Server list
RTObject_ptr RTC::RTObject_impl::getObjRef () const
[local interface] Get the object reference
Get CORBA object reference that has been set
Returns
The object reference
coil::Properties& RTC::RTObject_impl::getProperties ()
[local interface] Get RTC property
This operation returns the properties of the RTC. Empty property would be returned, if RTC has no property.
Returns
Property for RTC.
const char* RTC::RTObject_impl::getTypeName () [inline]
[local interface] Get type name
Get the type name has been set in ComponentProfile.
Returns
Type name
References m_profile, and RTC_TRACE.
const char* RTC::RTObject_impl::getVendor () [inline]
[local interface] Get vendor
Get the vendor information that has been set in ComponentProfile.
Returns
Vendor information
References m_profile, and RTC_TRACE.
const char* RTC::RTObject_impl::getVersion () [inline]
[local interface] Get version information
Get the version information that has been set in ComponentProfile.
Returns
Version information
References m_profile, and RTC_TRACE.
virtual ReturnCode_t RTC::RTObject_impl::initialize () throw (CORBA::SystemException) [virtual]
[CORBA interface] Initialize the RTC that realizes this interface.
The invocation of this operation shall result in the invocation of the callback ComponentAction::on_initialize.
Constraints
An RTC may be initialized only while it is in the Created state. Any attempt to invoke this operation while in another state shall fail with ReturnCode_t::PRECONDITION_NOT_MET.
Application developers are not expected to call this operation directly; it exists for use by the RTC infrastructure.
Returns
The return code of ReturnCode_t type
virtual CORBA::Boolean RTC::RTObject_impl::is_alive (ExecutionContext_ptr exec_context) throw (CORBA::SystemException) [virtual]
[CORBA interface] Confirm whether RTC is the alive state
A component is alive or not regardless of the execution context from which it is observed. However, whether or not it is Active, Inactive, or in Error is dependent on the execution context(s) in which it is running. That is, it may be Active in one context but Inactive in another. Therefore, this operation shall report whether this RTC is either Active, Inactive or in Error; which of those states a component is in with respect to a particular context may be queried from the context itself.
Returns
Result of Alive state confirmation
bool RTC::RTObject_impl::isOwnExecutionContext (RTC::UniqueId ec_id)
[local interface] Checking if the current context is own context
This function checks if the current context is own execution context. This function is assumed to be called from the following functions.
onStartup()
onShutdown()
onActivated()
onDeactivated()
onExecute()
onAborting()
onError()
onReset()
onStateUpdate()
onRateChanged()
The argument of this function should be the first argument (UniqueId ec_id) of the above functions.
Parameters
ec_id The above functions' first argument `exec_handle.`
Returns
true: Own context, false: other's context
virtual ReturnCode_t RTC::RTObject_impl::on_aborting (UniqueId exec_handle) throw (CORBA::SystemException) [virtual]
[ComponentAction CORBA interface] Transition to Error State
The RTC is transitioning from the Active state to the Error state in some execution context. This callback is invoked only a single time for time that the RTC transitions into the Error state from another state. This behavior is in contrast to that of on_error. As a result of this operation, onAborting() callback function is invoked.
Parameters
exec_handle ID of ExecutionContext that transited to the state
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::on_activated (UniqueId exec_handle) throw (CORBA::SystemException) [virtual]
[ComponentAction CORBA interface] Activate RTC
The RTC has been activated in the given execution context. As a result of this operation, onActivated() callback function is called.
Parameters
exec_handle ID of activation ExecutionContext
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::on_deactivated (UniqueId exec_handle) throw (CORBA::SystemException) [virtual]
[ComponentAction CORBA interface] Deactivate RTC
The RTC has been deactivated in the given execution context. As a result of this operation, onDeactivated() callback function is called.
Parameters
exec_handle ID of deactivation ExecutionContext
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::on_error (UniqueId exec_handle) throw (CORBA::SystemException) [virtual]
[ComponentAction CORBA interface] Error Processing of RTC
The RTC remains in the Error state. If the RTC is in the Error state relative to some execution context when it would otherwise be invoked from that context (according to the contexts ExecutionKind), this callback shall be invoked instead. For example,
If the ExecutionKind is PERIODIC, this operation shall be invoked in sorted order at the rate of the context instead of DataFlowComponentAction::on_execute and on_state_update.
If the ExecutionKind is EVENT_DRIVEN, this operation shall be invoked whenever FsmParticipantAction::on_action would otherwise have been invoked. As a result of this operation, onError() callback function is invoked.
Parameters
exec_handle ID of target ExecutionContext
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::on_execute (UniqueId exec_handle) throw (CORBA::SystemException) [virtual]
[DataFlowComponentAction CORBA interface] Primary Periodic Operation of RTC
This operation will be invoked periodically at the rate of the given execution context as long as the following conditions hold:
The RTC is Active.
The given execution context is Running This callback occurs during the first execution pass. As a result of this operation, onExecute() callback function is invoked.
Constraints
The execution context of the given context shall be PERIODIC.
Parameters
exec_handle ID of target ExecutionContext for Primary Periodic Operation
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::on_finalize () throw (CORBA::SystemException) [virtual]
[ComponentAction CORBA interface] Finalize RTC
The RTC is being destroyed. Any final RTC-specific tear-down logic should be performed here. As a result of this operation, onFinalize() callback function is called.
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::on_initialize () throw (CORBA::SystemException) [virtual]
[RTObject CORBA interface] Get ExecutionContextAdmin
This operation returns a list containing an ExecutionContextAdmin for every ExecutionContext owned by the RTC.
Returns
ExecutionContextService List
[ComponentAction CORBA interface] Initialize RTC The RTC has been initialized and entered the Alive state. Any RTC-specific initialization logic should be performed here. As a result of this operation, onInitialize() callback function is called.
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::on_rate_changed (UniqueId exec_handle) throw (CORBA::SystemException) [virtual]
[DataFlowComponentAction CORBA interface] Notify rate changed
This operation is a notification that the rate of the indicated execution context has changed. As a result of this operation, onRateChanged() callback function is called.
Constraints
The execution context of the given context shall be PERIODIC.
Parameters
exec_handle ID of target ExecutionContext for Operation
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::on_reset (UniqueId exec_handle) throw (CORBA::SystemException) [virtual]
[ComponentAction CORBA interface] Resetting RTC
The RTC is in the Error state. An attempt is being made to recover it such that it can return to the Inactive state. If the RTC was successfully recovered and can safely return to the Inactive state, this method shall complete with ReturnCode_t::OK. Any other result shall indicate that the RTC should remain in the Error state. As a result of this operation, onReset() callback function is invoked.
Parameters
exec_handle ID of target ExecutionContext for the reset
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::on_shutdown (UniqueId exec_handle) throw (CORBA::SystemException) [virtual]
[ComponentAction CORBA interface] Shutdown RTC
The given execution context, in which the RTC is participating, has transitioned from Running to Stopped. As a result of this operation, onShutdown() callback function is called.
Parameters
exec_handle ID of ExecutionContext that transited to the state
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::on_startup (UniqueId exec_handle) throw (CORBA::SystemException) [virtual]
[ComponentAction CORBA interface] Startup RTC
The given execution context, in which the RTC is participating, has transitioned from Stopped to Running. As a result of this operation, onStartup() callback function is called.
Parameters
exec_handle ID of ExecutionContext that transited to the state
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::on_state_update (UniqueId exec_handle) throw (CORBA::SystemException) [virtual]
[DataFlowComponentAction CORBA interface] Secondary Periodic Operation of RTC
This operation will be invoked periodically at the rate of the given execution context as long as the following conditions hold:
The RTC is Active.
The given execution context is Running This callback occurs during the second execution pass. As a result of this operation, onStateUpdate() callback function is invoked.
Constraints
The execution context of the given context shall be PERIODIC.
Parameters
exec_handle ID of target ExecutionContext for Secondary Periodic Operation
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::onAborting (RTC::UniqueId exec_handle) [protected, virtual]
Callback function to abort.
This is a callback function that is executed when ComponentAction::on_aborting was invoked.
 As for actual abortion of each component, since this function is dummy-implemented to return RTC::RTC_OK unconditionally, you need to implement this function by overriding it.
Parameters
exec_handle ID of the participant ExecutionContext
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::onActivated (RTC::UniqueId exec_handle) [protected, virtual]
Callback function to activate.
This is a callback function that is executed when ComponentAction::on_activated was invoked.
 As for actual activation of each component, since this function is dummy-implemented to return RTC::RTC_OK unconditionally, you need to implement this function by overriding it.
Parameters
exec_handle ID of the participant ExecutionContext
Returns
The return code of ReturnCode_t type
Reimplemented in RTC::PeriodicECSharedComposite .
void RTC::RTObject_impl::onAddPort (const PortProfile & pprof) [inline, protected]
References RTC::ADD_PORT, m_actionListeners, RTC::PortActionListenerHolder::notify(), and RTC::ComponentActionListeners::portaction_.
void RTC::RTObject_impl::onAttachExecutionContext (UniqueId ec_id) [inline, protected]
References RTC::EC_ATTACHED, RTC::ComponentActionListeners::ecaction_, m_actionListeners, and RTC::ExecutionContextActionListenerHolder::notify().
virtual ReturnCode_t RTC::RTObject_impl::onDeactivated (RTC::UniqueId exec_handle) [protected, virtual]
Callback function to deactivate.
This is a callback function that is executed when ComponentAction::on_deactivated was invoked.
 As for actual deactivation of each component, since this function is dummy-implemented to return RTC::RTC_OK unconditionally, you need to implement this function by overriding it.
Parameters
exec_handle ID of the participant ExecutionContext
Returns
The return code of ReturnCode_t type
Reimplemented in RTC::PeriodicECSharedComposite .
void RTC::RTObject_impl::onDetachExecutionContext (UniqueId ec_id) [inline, protected]
References RTC::EC_DETACHED, RTC::ComponentActionListeners::ecaction_, m_actionListeners, and RTC::ExecutionContextActionListenerHolder::notify().
virtual ReturnCode_t RTC::RTObject_impl::onError (RTC::UniqueId exec_handle) [protected, virtual]
Callback function for error handling.
This is a callback function that is executed when ComponentAction::on_error was invoked.
 As for actual error handling of each component, since this function is dummy-implemented to return RTC::RTC_OK unconditionally, you need to implement this function by overriding it.
Parameters
exec_handle ID of the participant ExecutionContext
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::onExecute (RTC::UniqueId exec_handle) [protected, virtual]
Callback function to execute periodically.
This is a callback function that is executed when DataFlowComponentAction::on_execute is invoked.
 As for actual periodic execution of each component, since this function is dummy-implemented to return RTC::RTC_OK unconditionally, you need to implement this function by overriding it. This function is invoked periodically as the first execution pass of Two-Pass Execution in Periodic Sampled Data Processing.
Parameters
exec_handle ID of the participant ExecutionContext
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::onFinalize () [protected, virtual]
Callback function to finalize.
This is a callback function that is executed when ComponentAction::on_finalize was invoked.
 As for actual finalization of each component, since this function is dummy-implemented to return RTC::RTC_OK unconditionally, you need to implement this function by overriding it.
Returns
The return code of ReturnCode_t type
Reimplemented in RTC::PeriodicECSharedComposite .
virtual ReturnCode_t RTC::RTObject_impl::onInitialize () [protected, virtual]
Callback function to initialize.
This is a callback function that is executed when ComponentAction::on_initialize was invoked.
 As for actual initialization of each component, since this function is dummy-implemented to return RTC::RTC_OK unconditionally, you need to implement this function by overriding it.
Returns
The return code of ReturnCode_t type
Reimplemented in RTC::PeriodicECSharedComposite .
virtual ReturnCode_t RTC::RTObject_impl::onRateChanged (RTC::UniqueId exec_handle) [protected, virtual]
Callback function to change execution cycle.
This is a callback function that is executed when DataFlowComponentAction::on_rate_changed was invoked.
 As for actual changing execution cycle of each component, since this function is dummy-implemented to return RTC::RTC_OK unconditionally, you need to implement this function by overriding it.
 This function is invoked when the execution of ExecutionContext was updated in Periodic Sampled Data Processing.
Parameters
exec_handle ID of the participant ExecutionContext
Returns
The return code of ReturnCode_t type
void RTC::RTObject_impl::onRemovePort (const PortProfile & pprof) [inline, protected]
References m_actionListeners, RTC::PortActionListenerHolder::notify(), RTC::ComponentActionListeners::portaction_, and RTC::REMOVE_PORT.
virtual ReturnCode_t RTC::RTObject_impl::onReset (RTC::UniqueId exec_handle) [protected, virtual]
Callback function to reset.
This is a callback function that is executed when ComponentAction::on_reset was invoked.
 As for actual reset of each component, since this function is dummy-implemented to return RTC::RTC_OK unconditionally, you need to implement this function by overriding it.
Parameters
exec_handle ID of the participant ExecutionContext
Returns
The return code of ReturnCode_t type
Reimplemented in RTC::PeriodicECSharedComposite .
virtual ReturnCode_t RTC::RTObject_impl::onShutdown (RTC::UniqueId exec_handle) [protected, virtual]
Callback function for shutdown action.
Callback function that is executed when ComponentAction::on_shutdown was invoked.
 As for actual shutdown of each component, since this function is dummy-implemented to return RTC::RTC_OK unconditionally, you need to implement this function by overriding it.
Parameters
exec_handle ID of the participant ExecutionContext
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::onStartup (RTC::UniqueId exec_handle) [protected, virtual]
Callback function for startup action.
Callback function that is executed when ComponentAction::on_startup was invoked.
 As for actual startup of each component, since this function is dummy-implemented to return RTC::RTC_OK unconditionally, you need to implement this function by overriding it.
Parameters
exec_handle ID of the participant ExecutionContext
Returns
The return code of ReturnCode_t type
virtual ReturnCode_t RTC::RTObject_impl::onStateUpdate (RTC::UniqueId exec_handle) [protected, virtual]
Callback function to update the state.
This is a callback function that is executed when DataFlowComponentAction::on_state_update was invoked.
 As for actual updating the state of each component, since this function is dummy-implemented to return RTC::RTC_OK unconditionally, you need to implement this function by overriding it.
 This function is invoked periodically as the second execution pass of Two-Pass Execution in Periodic Sampled Data Processing.
Parameters
exec_handle ID of the participant ExecutionContext
Returns
The return code of ReturnCode_t type
void RTC::RTObject_impl::postOnAborting (UniqueId ec_id, ReturnCode_t ret) [inline, protected]
References m_actionListeners, RTC::PostComponentActionListenerHolder::notify(), RTC::POST_ON_ABORTING, and RTC::ComponentActionListeners::postaction_.
void RTC::RTObject_impl::postOnActivated (UniqueId ec_id, ReturnCode_t ret) [inline, protected]
References m_actionListeners, RTC::PostComponentActionListenerHolder::notify(), RTC::POST_ON_ACTIVATED, and RTC::ComponentActionListeners::postaction_.
void RTC::RTObject_impl::postOnDeactivated (UniqueId ec_id, ReturnCode_t ret) [inline, protected]
References m_actionListeners, RTC::PostComponentActionListenerHolder::notify(), RTC::POST_ON_DEACTIVATED, and RTC::ComponentActionListeners::postaction_.
void RTC::RTObject_impl::postOnError (UniqueId ec_id, ReturnCode_t ret) [inline, protected]
References m_actionListeners, RTC::PostComponentActionListenerHolder::notify(), RTC::POST_ON_ERROR, and RTC::ComponentActionListeners::postaction_.
void RTC::RTObject_impl::postOnExecute (UniqueId ec_id, ReturnCode_t ret) [inline, protected]
References m_actionListeners, RTC::PostComponentActionListenerHolder::notify(), RTC::POST_ON_EXECUTE, and RTC::ComponentActionListeners::postaction_.
void RTC::RTObject_impl::postOnFinalize (UniqueId ec_id, ReturnCode_t ret) [inline, protected]
References m_actionListeners, RTC::PostComponentActionListenerHolder::notify(), RTC::POST_ON_FINALIZE, and RTC::ComponentActionListeners::postaction_.
void RTC::RTObject_impl::postOnInitialize (UniqueId ec_id, ReturnCode_t ret) [inline, protected]
References m_actionListeners, RTC::PostComponentActionListenerHolder::notify(), RTC::POST_ON_INITIALIZE, and RTC::ComponentActionListeners::postaction_.
void RTC::RTObject_impl::postOnRateChanged (UniqueId ec_id, ReturnCode_t ret) [inline, protected]
References m_actionListeners, RTC::PostComponentActionListenerHolder::notify(), RTC::POST_ON_RATE_CHANGED, and RTC::ComponentActionListeners::postaction_.
void RTC::RTObject_impl::postOnReset (UniqueId ec_id, ReturnCode_t ret) [inline, protected]
References m_actionListeners, RTC::PostComponentActionListenerHolder::notify(), RTC::POST_ON_RESET, and RTC::ComponentActionListeners::postaction_.
void RTC::RTObject_impl::postOnShutdown (UniqueId ec_id, ReturnCode_t ret) [inline, protected]
References m_actionListeners, RTC::PostComponentActionListenerHolder::notify(), RTC::POST_ON_SHUTDOWN, and RTC::ComponentActionListeners::postaction_.
void RTC::RTObject_impl::postOnStartup (UniqueId ec_id, ReturnCode_t ret) [inline, protected]
References m_actionListeners, RTC::PostComponentActionListenerHolder::notify(), RTC::POST_ON_STARTUP, and RTC::ComponentActionListeners::postaction_.
void RTC::RTObject_impl::postOnStateUpdate (UniqueId ec_id, ReturnCode_t ret) [inline, protected]
References m_actionListeners, RTC::PostComponentActionListenerHolder::notify(), RTC::POST_ON_STATE_UPDATE, and RTC::ComponentActionListeners::postaction_.
void RTC::RTObject_impl::preOnAborting (UniqueId ec_id) [inline, protected]
References m_actionListeners, RTC::PreComponentActionListenerHolder::notify(), RTC::PRE_ON_ABORTING, and RTC::ComponentActionListeners::preaction_.
void RTC::RTObject_impl::preOnActivated (UniqueId ec_id) [inline, protected]
References m_actionListeners, RTC::PreComponentActionListenerHolder::notify(), RTC::PRE_ON_ACTIVATED, and RTC::ComponentActionListeners::preaction_.
void RTC::RTObject_impl::preOnDeactivated (UniqueId ec_id) [inline, protected]
References m_actionListeners, RTC::PreComponentActionListenerHolder::notify(), RTC::PRE_ON_DEACTIVATED, and RTC::ComponentActionListeners::preaction_.
void RTC::RTObject_impl::preOnError (UniqueId ec_id) [inline, protected]
References m_actionListeners, RTC::PreComponentActionListenerHolder::notify(), RTC::PRE_ON_ERROR, and RTC::ComponentActionListeners::preaction_.
void RTC::RTObject_impl::preOnExecute (UniqueId ec_id) [inline, protected]
References m_actionListeners, RTC::PreComponentActionListenerHolder::notify(), RTC::PRE_ON_EXECUTE, and RTC::ComponentActionListeners::preaction_.
void RTC::RTObject_impl::preOnFinalize (UniqueId ec_id) [inline, protected]
References m_actionListeners, RTC::PreComponentActionListenerHolder::notify(), RTC::PRE_ON_FINALIZE, and RTC::ComponentActionListeners::preaction_.
void RTC::RTObject_impl::preOnInitialize (UniqueId ec_id) [inline, protected]
References m_actionListeners, RTC::PreComponentActionListenerHolder::notify(), RTC::PRE_ON_INITIALIZE, and RTC::ComponentActionListeners::preaction_.
void RTC::RTObject_impl::preOnRateChanged (UniqueId ec_id) [inline, protected]
References m_actionListeners, RTC::PreComponentActionListenerHolder::notify(), RTC::PRE_ON_RATE_CHANGED, and RTC::ComponentActionListeners::preaction_.
void RTC::RTObject_impl::preOnReset (UniqueId ec_id) [inline, protected]
References m_actionListeners, RTC::PreComponentActionListenerHolder::notify(), RTC::PRE_ON_RESET, and RTC::ComponentActionListeners::preaction_.
void RTC::RTObject_impl::preOnShutdown (UniqueId ec_id) [inline, protected]
References m_actionListeners, RTC::PreComponentActionListenerHolder::notify(), RTC::PRE_ON_SHUTDOWN, and RTC::ComponentActionListeners::preaction_.
void RTC::RTObject_impl::preOnStartup (UniqueId ec_id) [inline, protected]
References m_actionListeners, RTC::PreComponentActionListenerHolder::notify(), RTC::PRE_ON_STARTUP, and RTC::ComponentActionListeners::preaction_.
void RTC::RTObject_impl::preOnStateUpdate (UniqueId ec_id) [inline, protected]
References m_actionListeners, RTC::PreComponentActionListenerHolder::notify(), RTC::PRE_ON_STATE_UPDATE, and RTC::ComponentActionListeners::preaction_.
bool RTC::RTObject_impl::readAll ()
Readout the value from All InPorts.
This operation read the value from all InPort registered in the RTC.
Returns
result (Successful:true, Failed:false)
void RTC::RTObject_impl::registerInPort (const char * name, InPortBase & inport)
[local interface] Register DataInPort
This operation registers DataInPort held by this RTC. Set `port.dataport` and `tcp_any` to property of Port, and create instances of DataInPort and register it.
Parameters
name Port name
inport DataInPort which is registered to the RTC
void RTC::RTObject_impl::registerOutPort (const char * name, OutPortBase & outport)
[local interface] Register DataOutPort
This operation registers DataOutPor held by this RTC. Set `port.dataport` and `tcp_any` to property of Port, and then create instances of DataOutPort and register it.
Parameters
name Port name
outport DataOutPort which is registered to the RTC
void RTC::RTObject_impl::registerPort (CorbaPort & port)
[local interface] Register Port
This operation registers a Port held by this RTC. In order to enable access to the Port from outside of RTC, the Port must be registered by this operation. The Port that is registered by this operation would be identified by PortProfile.name in the inside of RTC. Therefore, the Port should have unique PortProfile.name in the RTC. The registering Port would be activated properly, and the reference and the object reference would be stored in lists in RTC.
Parameters
port Port which is registered to the RTC
void RTC::RTObject_impl::registerPort (PortService_ptr port)
[local interface] Register Port
This operation registers a Port held by this RTC. In order to enable access to the Port from outside of RTC, the Port must be registered by this operation. The Port that is registered by this operation would be identified by PortProfile.name in the inside of RTC. Therefore, the Port should have unique PortProfile.name in the RTC. The registering Port would be activated properly, and the reference and the object reference would be stored in lists in RTC.
Parameters
port Port which is registered to the RTC
void RTC::RTObject_impl::registerPort (PortBase & port)
[local interface] Register Port
This operation registers a Port held by this RTC. In order to enable access to the Port from outside of RTC, the Port must be registered by this operation. The Port that is registered by this operation would be identified by PortProfile.name in the inside of RTC. Therefore, the Port should have unique PortProfile.name in the RTC. The registering Port would be activated properly, and the reference and the object reference would be stored in lists in RTC.
Parameters
port Port which is registered to the RTC
void RTC::RTObject_impl::removeConfigurationParamListener (ConfigurationParamListenerType type, ConfigurationParamListener * listener)
Removing ConfigurationParamListener.
This function removes a listener object which is added by addConfigurationParamListener() function.
Parameters
type ConfigurationParamListenerType value ON_UPDATE_CONFIG_PARAM is only allowed.
listener a pointer to ConfigurationParamListener listener object.
void RTC::RTObject_impl::removeConfigurationSetListener (ConfigurationSetListenerType type, ConfigurationSetListener * listener)
Removing ConfigurationSetListener.
This function removes a listener object which is added by addConfigurationSetListener() function.
Parameters
type ConfigurationSetListenerType value
listener a pointer to ConfigurationSetListener listener object.
void RTC::RTObject_impl::removeConfigurationSetNameListener (ConfigurationSetNameListenerType type, ConfigurationSetNameListener * listener)
Removing ConfigurationSetNameListener.
This function removes a listener object which is added by addConfigurationSetNameListener() function.
Parameters
type ConfigurationSetNameListenerType value ON_UPDATE_CONFIG_PARAM is only allowed.
listener a pointer to ConfigurationSetNameListener listener object.
void RTC::RTObject_impl::removeExecutionContextActionListener (ECActionListenerType listener_type, ECActionListener * listener)
Removing ExecutionContextAction type listener.
This operation removes a specified listener.
Parameters
listener_type A listener type
listener A pointer to a listener object
bool RTC::RTObject_impl::removeInPort (InPortBase & port)
[local interface] Unregister InPort
This operation unregisters a InPort held by this RTC.
Parameters
port Port which is unregistered
Returns
Unregister result (Successful:true, Failed:false)
bool RTC::RTObject_impl::removeOutPort (OutPortBase & port)
[local interface] Unregister OutPort
This operation unregisters a OutPort held by this RTC.
Parameters
port Port which is unregistered
Returns
Unregister result (Successful:true, Failed:false)
bool RTC::RTObject_impl::removePort (CorbaPort & port)
[local interface] Unregister Port
This operation unregisters a Port held by this RTC.
Parameters
port Port which is unregistered
Returns
Unregister result (Successful:true, Failed:false)
bool RTC::RTObject_impl::removePort (PortService_ptr port)
[local interface] Unregister Port
This operation unregisters a Port held by this RTC.
Parameters
port Port which is unregistered
Returns
Unregister result (Successful:true, Failed:false)
bool RTC::RTObject_impl::removePort (PortBase & port)
[local interface] Unregister Port
This operation unregisters a Port held by this RTC.
Parameters
port Port which is unregistered
Returns
Unregister result (Successful:true, Failed:false)
void RTC::RTObject_impl::removePortActionListener (PortActionListenerType listener_type, PortActionListener * listener)
Removing PortAction type listener.
This operation removes a specified listener.
Parameters
listener_type A listener type
listener A pointer to a listener object
void RTC::RTObject_impl::removePortConnectListener (PortConnectListenerType listener_type, PortConnectListener * listener)
Removing PortConnect type listener.
This operation removes a specified listener.
Parameters
listener_type A listener type
listener A pointer to a listener object
void RTC::RTObject_impl::removePortConnectRetListener (PortConnectRetListenerType listener_type, PortConnectRetListener * listener)
Removing PortConnectRet type listener.
This operation removes a specified listener.
Parameters
listener_type A listener type
listener A pointer to a listener object
void RTC::RTObject_impl::removePostComponentActionListener (PostComponentActionListenerType listener_type, PostComponentActionListener * listener)
Removing PostComponentAction type listener.
This operation removes a specified listener.
Parameters
listener_type A listener type
listener A pointer to a listener object
void RTC::RTObject_impl::removePreComponentActionListener (PreComponentActionListenerType listener_type, PreComponentActionListener * listener)
Removing PreComponentAction type listener.
This operation removes a specified listener.
Parameters
listener_type A listener type
listener A pointer to a listener object
bool RTC::RTObject_impl::removeSdoServiceConsumer (const char * id)
[local interface] Remove a SDO service provider
bool RTC::RTObject_impl::removeSdoServiceProvider (const char * id)
[local interface] Remove a SDO service provider
ReturnCode_t RTC::RTObject_impl::reset (RTC::UniqueId ec_id)
[local interface] Resetting and go to Inactive state
This function reset RTC and makes transition from Error to Inactive state. This function is assumed to be called from the following functions.
onError()
The argument of this function should be the first argument (UniqueId ec_id) of the above function.
Parameters
ec_id The above functions' first argument `exec_handle.`
Returns
Return code
ReturnCode_t RTC::RTObject_impl::setExecutionRate (RTC::UniqueId ec_id, double rate)
[local interface] Setting current context' execution rate
This function sets a execution rate in the context. If this context's kind is not PERIODC, behavior is not defined. This function is assumed to be called from the following functions.
onStartup()
onShutdown()
onActivated()
onDeactivated()
onExecute()
onAborting()
onError()
onReset()
onStateUpdate()
onRateChanged()
The argument of this function should be the first argument (UniqueId ec_id) of the above functions.
Parameters
ec_id The above functions' first argument `exec_handle.`
rate Execution rate in [Hz].
void RTC::RTObject_impl::setInstanceName (const char * instance_name)
[local interface] Set instance name
Set the instance name specified in ComponentProfile.
Parameters
instance_name Instance name
void RTC::RTObject_impl::setObjRef (const RTObject_ptr rtobj)
[local interface] Set the object reference
Set RTC's CORBA object reference.
Parameters
rtobj The object reference
void RTC::RTObject_impl::setProperties (const coil::Properties & prop)
[local interface] Set RTC property
This operation sets the properties to the RTC. The given property values should include information for ComponentProfile. Generally, this operation is designed to be called from Manager, when RTC is initialized
Parameters
prop Property for RTC.
void RTC::RTObject_impl::setReadAll (bool read = true, bool completion = false)
Set whether to execute the readAll() method.
Set whether to execute the readAll() method.
Parameters
read(default:true) (readAll() is called:true, readAll() isn't called:false)
completion(default:false) All InPort::read() calls are completed.:true, If one InPort::read() is False, return false.:false
completion(default:false)
void RTC::RTObject_impl::setWriteAll (bool write = true, bool completion = false)
Set whether to execute the writeAll() method.
Set whether to execute the writeAll() method.
Parameters
write(default:true) (writeAll() is called:true, writeAll() isn't called:false)
completion(default:false) All OutPort::write() calls are completed.:true, If one OutPort::write() is False, return false.:false
void RTC::RTObject_impl::shutdown () [protected]
Shutdown RTC.
This operation ececutes RTC's termination. This unregisters all Ports, deactivates corresponding CORBA objects and shuts down RTC.
void RTC::RTObject_impl::updateParameters (const char * config_set)
Update configuration parameters (by ID).
Update configuration parameter value by the value that set to a configuration set of specified ID.
Parameters
config_set The target configuration set's ID for setup
bool RTC::RTObject_impl::writeAll ()
The write() method of all OutPort is called.
This operation call the write() method of all OutPort registered in the RTC.
Returns
result (Successful:true, Failed:false)
Member Data Documentation
ComponentActionListeners RTC::RTObject_impl::m_actionListeners [protected]
ComponentActionListener holder.
Holders of ComponentActionListeners
Referenced by onAddPort(), onAttachExecutionContext(), onDetachExecutionContext(), onRemovePort(), postOnAborting(), postOnActivated(), postOnDeactivated(), postOnError(), postOnExecute(), postOnFinalize(), postOnInitialize(), postOnRateChanged(), postOnReset(), postOnShutdown(), postOnStartup(), postOnStateUpdate(), preOnAborting(), preOnActivated(), preOnDeactivated(), preOnError(), preOnExecute(), preOnFinalize(), preOnInitialize(), preOnRateChanged(), preOnReset(), preOnShutdown(), preOnStartup(), and preOnStateUpdate().
ConfigAdmin RTC::RTObject_impl::m_configsets [protected]
Configuration Administrator Object.
Referenced by bindParameter().
bool RTC::RTObject_impl::m_created [protected]
Created Status Flag.
std::vector<ExecutionContextBase*> RTC::RTObject_impl::m_eclist [protected]
List of ExecutionContextBase.
ExecutionContextServiceList RTC::RTObject_impl::m_ecMine [protected]
List of owned ExecutionContextService.
ExecutionContextServiceList RTC::RTObject_impl::m_ecOther [protected]
List of participating ExecutionContextService.
bool RTC::RTObject_impl::m_exiting [protected]
RTC Finalize Status Flag.
std::vector<InPortBase*> RTC::RTObject_impl::m_inports [protected]
List of InPortBase*.
RTObject_var RTC::RTObject_impl::m_objref [protected]
Object reference.
std::vector<OutPortBase*> RTC::RTObject_impl::m_outports [protected]
List of OutPortBase*.
Manager* RTC::RTObject_impl::m_pManager [protected]
Manager object.
CORBA::ORB_var RTC::RTObject_impl::m_pORB [protected]
The pointer to the ORB.
PortAdmin RTC::RTObject_impl::m_portAdmin [protected]
List of Port Object reference.
PortConnectListeners RTC::RTObject_impl::m_portconnListeners [protected]
PortConnectListener holder.
Holders of PortConnectListeners
PortableServer::POA_var RTC::RTObject_impl::m_pPOA [protected]
The pointer to the POA.
ComponentProfile RTC::RTObject_impl::m_profile [protected]
ComponentProfile.
Referenced by getCategory(), getDescription(), getInstanceName(), getTypeName(), getVendor(), and getVersion().
coil::Properties RTC::RTObject_impl::m_properties [protected]
Alive Status Flag.
RTC's Property
SDOPackage::Configuration_var RTC::RTObject_impl::m_pSdoConfig [protected]
The pointer to the SDO Configuration Interface.
SDOPackage::Configuration_impl* RTC::RTObject_impl::m_pSdoConfigImpl [protected]
The pointer to the SDO Configuration Object.
bool RTC::RTObject_impl::m_readAll [protected]
flag for readAll()
bool RTC::RTObject_impl::m_readAllCompletion [protected]
flag for readAll()
true:Even if the error occurs during readAll(), it executes it to the last minute. false:End when error occurs during readAll().
SDOPackage::OrganizationList RTC::RTObject_impl::m_sdoOrganizations [protected]
SDO organization.
SDOPackage::OrganizationList RTC::RTObject_impl::m_sdoOwnedOrganizations [protected]
SDO owned organization list.
SdoServiceAdmin RTC::RTObject_impl::m_sdoservice [protected]
SDO Service Administrator Object.
SDOPackage::NVList RTC::RTObject_impl::m_sdoStatus [protected]
SDO Status.
bool RTC::RTObject_impl::m_writeAll [protected]
flag for writeAll()
bool RTC::RTObject_impl::m_writeAllCompletion [protected]
flag for writeAll()
true:Even if the error occurs during writeAll(), it executes it to the last minute. false:End when error occurs during writeAll().
Logger RTC::RTObject_impl::rtclog [mutable, protected]
Logger stream.