coil::TaskFunc< T, F > Class Template Reference
TaskFunc template class.
#include <PeriodicTaskBase.h>
Public Member Functions
TaskFunc (T *obj, F func)
Constructor.
virtual ~TaskFunc ()
Destructor.
virtual int operator() ()
Functor.
Public Attributes
T * m_obj
object
F m_func
function
Detailed Description
template<typename T, typename F = int (*)()> class coil::TaskFunc< T, F >
TaskFunc template class.
Constructor & Destructor Documentation
template<typename T , typename F = int (*)()> coil::TaskFunc< T, F >::TaskFunc (T * obj, F func) [inline]
Constructor.
Constructor
Parameters
obj Object.
func Function.
template<typename T , typename F = int (*)()> virtual coil::TaskFunc< T, F >::~TaskFunc () [inline, virtual]
Destructor.
Destructor
Member Function Documentation
template<typename T , typename F = int (*)()> virtual int coil::TaskFunc< T, F >::operator() () [inline, virtual]
Functor.
Execute a function of the object.
Implements coil::TaskFuncBase .
References coil::TaskFunc< T, F >::m_func, and coil::TaskFunc< T, F >::m_obj.
Member Data Documentation
template<typename T , typename F = int (*)()> F coil::TaskFunc< T, F >::m_func
function
Referenced by coil::TaskFunc< T, F >::operator()().
template<typename T , typename F = int (*)()> T* coil::TaskFunc< T, F >::m_obj
object
Referenced by coil::TaskFunc< T, F >::operator()().