RTC::CorbaConsumerBase Class Reference
#include <CorbaConsumer.h>
Public Member Functions
CorbaConsumerBase ()
Consructor.
CorbaConsumerBase (const CorbaConsumerBase &x)
Copy Consructor.
CorbaConsumerBase & operator= (const CorbaConsumerBase &x)
Assignment operator.
void swap (CorbaConsumerBase &x)
swap function
virtual ~CorbaConsumerBase (void)
Virtual destructor.
virtual bool setObject (CORBA::Object_ptr obj)
Set CORBA Object.
virtual CORBA::Object_ptr getObject ()
Get CORBA Object.
virtual void releaseObject ()
Clear CORBA object setting.
Protected Attributes
CORBA::Object_var m_objref
CORBA object which is set.
Constructor & Destructor Documentation
RTC::CorbaConsumerBase::CorbaConsumerBase () [inline]
Consructor.
RTC::CorbaConsumerBase::CorbaConsumerBase (const CorbaConsumerBase & x) [inline]
Copy Consructor.
Parameters
x A CorbaConsumerBase object of copy source
virtual RTC::CorbaConsumerBase::~CorbaConsumerBase (void) [inline, virtual]
Virtual destructor.
References releaseObject().
Member Function Documentation
virtual CORBA::Object_ptr RTC::CorbaConsumerBase::getObject () [inline, virtual]
Get CORBA Object.
Get the object reference held as CORBA::Object_var type in ConsumerBase object.
Returns
Object reference of CORBA object
References m_objref.
CorbaConsumerBase& RTC::CorbaConsumerBase::operator= (const CorbaConsumerBase & x) [inline]
Assignment operator.
Parameters
x Copy source.
Returns
An assignment result
References swap().
virtual void RTC::CorbaConsumerBase::releaseObject () [inline, virtual]
Clear CORBA object setting.
Clear CORBA object which is set. Operate nothing for CORBA object itself.
Reimplemented in RTC::CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar > , RTC::CorbaConsumer< ::OpenRTM::InPortCdr > , and RTC::CorbaConsumer< ::OpenRTM::OutPortCdr > .
References m_objref.
Referenced by ~CorbaConsumerBase().
virtual bool RTC::CorbaConsumerBase::setObject (CORBA::Object_ptr obj) [inline, virtual]
Set CORBA Object.
The given CORBA Object is held as CORBA::Object_var type in ConsumerBase object.
Parameters
obj Object reference of CORBA object
Returns
If obj is nil reference, it returns false.
Reimplemented in RTC::CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar > , RTC::CorbaConsumer< ::OpenRTM::InPortCdr > , and RTC::CorbaConsumer< ::OpenRTM::OutPortCdr > .
References m_objref.
Referenced by RTC::CorbaConsumer< ::OpenRTM::OutPortCdr >::setObject().
void RTC::CorbaConsumerBase::swap (CorbaConsumerBase & x) [inline]
swap function
Parameters
x Copy source.
References m_objref.
Referenced by operator=().
Member Data Documentation
CORBA::Object_var RTC::CorbaConsumerBase::m_objref [protected]
CORBA object which is set.
Referenced by getObject(), releaseObject(), RTC::CorbaConsumer< ::OpenRTM::OutPortCdr >::setObject(), setObject(), and swap().