RTC::PreComponentActionListenerHolder Class Reference
PreComponentActionListener holder class.
#include <ComponentActionListener.h>
Public Member Functions
PreComponentActionListenerHolder ()
Constructor.
virtual ~PreComponentActionListenerHolder ()
Destructor.
void addListener (PreComponentActionListener *listener, bool autoclean)
Add the listener.
void removeListener (PreComponentActionListener *listener)
Remove the listener.
void notify (UniqueId ec_id)
Notify listeners.
Detailed Description
PreComponentActionListener holder class. This class manages one ore more instances of PreComponentActionListener class.
Constructor & Destructor Documentation
RTC::PreComponentActionListenerHolder::PreComponentActionListenerHolder ()
Constructor.
virtual RTC::PreComponentActionListenerHolder::~PreComponentActionListenerHolder () [virtual]
Destructor.
Member Function Documentation
void RTC::PreComponentActionListenerHolder::addListener (PreComponentActionListener * listener, bool autoclean)
Add the listener.
This method adds the listener.
Parameters
listener Added listener
autoclean true:The listener is deleted at the destructor., false:The listener is not deleted at the destructor.
void RTC::PreComponentActionListenerHolder::notify (UniqueId ec_id)
Notify listeners.
This calls the Callback method of the registered listener.
Parameters
info ConnectorInfo
Referenced by RTC::RTObject_impl::preOnAborting(), RTC::RTObject_impl::preOnActivated(), RTC::RTObject_impl::preOnDeactivated(), RTC::RTObject_impl::preOnError(), RTC::RTObject_impl::preOnExecute(), RTC::RTObject_impl::preOnFinalize(), RTC::RTObject_impl::preOnInitialize(), RTC::RTObject_impl::preOnRateChanged(), RTC::RTObject_impl::preOnReset(), RTC::RTObject_impl::preOnShutdown(), RTC::RTObject_impl::preOnStartup(), and RTC::RTObject_impl::preOnStateUpdate().
void RTC::PreComponentActionListenerHolder::removeListener (PreComponentActionListener * listener)
Remove the listener.
This method removes the listener.
Parameters
listener Removed listener