RTC::FactoryBase Class Reference
FactoryBase base class.
#include <Factory.h>
Public Member Functions
FactoryBase (const coil::Properties &profile)
Constructor.
virtual ~FactoryBase (void)
Destructor.
virtual RTObject_impl * create (Manager *mgr)=0
Create components.
virtual void destroy (RTObject_impl *comp)=0
Destroy components.
virtual coil::Properties & profile ()
Get the component profile.
virtual int number ()
Get the number of current instances.
Protected Attributes
coil::Properties m_Profile
Component profile.
int m_Number
Number of current RT-Component's instances.
Detailed Description
FactoryBase base class. This is a base class for RT-Component factory.
Since
0.2.0
Constructor & Destructor Documentation
RTC::FactoryBase::FactoryBase (const coil::Properties & profile)
Constructor.
Constructor.
Parameters
profile Component profile
virtual RTC::FactoryBase::~FactoryBase (void) [virtual]
Destructor.
Destructor
Member Function Documentation
virtual RTObject_impl* RTC::FactoryBase::create (Manager * mgr) [pure virtual]
Create components.
Pure virtual function to create RT-Component's instances
Parameters
mgr Manager object
Returns
Created RT-Components
Implemented in RTC::FactoryCXX .
virtual void RTC::FactoryBase::destroy (RTObject_impl * comp) [pure virtual]
Destroy components.
Pure virtual function to destroy RT-Component's instances
Parameters
comp The target RT-Component for destruction
Implemented in RTC::FactoryCXX .
virtual int RTC::FactoryBase::number () [virtual]
Get the number of current instances.
Get the number of current RT-Component's instances.
Returns
Number of RT-Component's instances
virtual coil::Properties& RTC::FactoryBase::profile () [virtual]
Get the component profile.
Get the component profile.
Returns
The component profile
Referenced by RTC::Manager::ModuleFactories::operator()(), and RTC::Manager::FactoryPredicate::operator()().
Member Data Documentation
int RTC::FactoryBase::m_Number [protected]
Number of current RT-Component's instances.
coil::Properties RTC::FactoryBase::m_Profile [protected]
Component profile.