RTC::Manager::OrbRunner Class Reference
OrbRunner class.
#include <Manager.h>
Public Member Functions
OrbRunner (CORBA::ORB_ptr orb)
Constructor.
virtual int open (void *args)
ORB activation processing.
virtual int svc (void)
ORB start processing.
virtual int close (unsigned long flags)
ORB close processing.
Detailed Description
OrbRunner class. ORB exrcution helper class
Since
0.4.0
Constructor & Destructor Documentation
RTC::Manager::OrbRunner::OrbRunner (CORBA::ORB_ptr orb) [inline]
Constructor.
Constructor
References open().
Member Function Documentation
virtual int RTC::Manager::OrbRunner::close (unsigned long flags) [inline, virtual]
ORB close processing.
ORB close processing.
Parameters
flags Flag of close processing
Returns
Close result
Reimplemented from coil::Task .
virtual int RTC::Manager::OrbRunner::open (void * args) [inline, virtual]
ORB activation processing.
ORB activation processing.
Parameters
args ORB activation processing
Returns
Activation result
Reimplemented from coil::Task .
References coil::Task::activate().
Referenced by OrbRunner().
virtual int RTC::Manager::OrbRunner::svc (void) [inline, virtual]
ORB start processing.
ORB start processing
Returns
Starting result
Reimplemented from coil::Task .