RTC::ConnectorDataListenerT< DataType > Class Template Reference
ConnectorDataListenerT class.
#include <ConnectorListener.h>
Public Member Functions
virtual ~ConnectorDataListenerT ()
Destructor.
virtual void operator() (const ConnectorInfo &info, const cdrMemoryStream &cdrdata)
Callback method.
virtual void operator() (const ConnectorInfo &info, const DataType &data)=0
Virtual Callback method.
Detailed Description
template<class DataType> class RTC::ConnectorDataListenerT< DataType >
ConnectorDataListenerT class. This class is abstract base class for listener classes that provides callbacks for various events in the data port's connectors.
This class template can have practical data types that are used as typed variable for DataPort as an argument of template instead of cdrMemoryStream.
Constructor & Destructor Documentation
template<class DataType > virtual RTC::ConnectorDataListenerT< DataType >::~ConnectorDataListenerT () [inline, virtual]
Destructor.
Member Function Documentation
template<class DataType > virtual void RTC::ConnectorDataListenerT< DataType >::operator() (const ConnectorInfo & info, const DataType & data) [pure virtual]
Virtual Callback method.
This method invokes the callback method of ConnectorDataListenerT. Data is converted into the variable type used in DataPort.
template<class DataType > virtual void RTC::ConnectorDataListenerT< DataType >::operator() (const ConnectorInfo & info, const cdrMemoryStream & cdrdata) [inline, virtual]
Callback method.
This method invokes the callback method of ConnectorDataListenerT. Data is converted into the variable type used in DataPort.
Parameters
info ConnectorInfo
cdrdata Data of cdrMemoryStream type
Implements RTC::ConnectorDataListener .
References coil::Properties::getProperty(), coil::normalize(), RTC::ConnectorInfo::properties, and coil::split().