coil::Task Class Reference
Task class.
#include <Task.h>
Public Member Functions
Task ()
Constructor.
virtual ~Task ()
Destructor.
virtual int open (void *args=0)
Task open.
virtual int close (unsigned long flags=0)
Task close.
virtual int svc ()
Execute thread.
virtual void activate ()
Create a thread.
virtual int wait (void)
Waiting for the thread terminate.
virtual int suspend (void)
Suspending the task.
virtual int resume (void)
Resuming the suspended task.
virtual void reset ()
Reset of task count.
virtual void finalize ()
Static Public Member Functions
static void * svc_run (void *args=0)
Start thread Execution.
Detailed Description
Task class.
Constructor & Destructor Documentation
coil::Task::Task ()
Constructor.
Constructor
virtual coil::Task::~Task () [virtual]
Destructor.
Destructor
Member Function Documentation
virtual void coil::Task::activate () [virtual]
Create a thread.
Create a thread
Reimplemented in coil::PeriodicTask , and coil::PeriodicTaskBase .
Referenced by coil::Async_ref_t< Object, Func >::invoke(), coil::Async_t< Object, Func >::invoke(), RTC::Manager::Terminator::open(), and RTC::Manager::OrbRunner::open().
virtual int coil::Task::close (unsigned long flags = 0) [virtual]
Task close.
Task close
Parameters
flags Flags
Reimplemented in RTC::Manager::OrbRunner , and RTC::PeriodicExecutionContext .
virtual void coil::Task::finalize () [virtual]
Finalizing the task.
Reimplemented in coil::Async_t< Object, Func > , coil::Async_ref_t< Object, Func > , coil::PeriodicTask , and coil::PeriodicTaskBase .
virtual int coil::Task::open (void * args = 0) [virtual]
Task open.
Task open
Parameters
args Arguments
Reimplemented in coil::Timer , RTC::Manager::OrbRunner , RTC::Manager::Terminator , and RTC::PeriodicExecutionContext .
virtual void coil::Task::reset () [virtual]
Reset of task count.
Reset of task count
virtual int coil::Task::resume (void) [virtual]
Resuming the suspended task.
Resuming the suspended task
Reimplemented in coil::PeriodicTask , and coil::PeriodicTaskBase .
virtual int coil::Task::suspend (void) [virtual]
Suspending the task.
Suspending the task
Reimplemented in coil::PeriodicTask , and coil::PeriodicTaskBase .
virtual int coil::Task::svc () [virtual]
Execute thread.
Execute thread
Reimplemented in coil::Async_t< Object, Func > , coil::Async_ref_t< Object, Func > , coil::PeriodicTask , coil::Timer , RTC::ExtTrigExecutionContext , RTC::Manager::OrbRunner , RTC::Manager::Terminator , RTC::OpenHRPExecutionContext , and RTC::PeriodicExecutionContext .
static void* coil::Task::svc_run (void * args = 0) [static]
Start thread Execution.
Start thread Execution
Parameters
args Thread arguments
virtual int coil::Task::wait (void) [virtual]
Waiting for the thread terminate.
Waiting for the thread terminate