RTC::PostComponentActionListenerHolder Class Reference
PostComponentActionListener holder class.
#include <ComponentActionListener.h>
Public Member Functions
PostComponentActionListenerHolder ()
Constructor.
virtual ~PostComponentActionListenerHolder ()
Destructor.
void addListener (PostComponentActionListener *listener, bool autoclean)
Add the listener.
void removeListener (PostComponentActionListener *listener)
Remove the listener.
void notify (UniqueId ec_id, ReturnCode_t ret)
Notify listeners.
Detailed Description
PostComponentActionListener holder class. This class manages one ore more instances of PostComponentActionListener class.
Constructor & Destructor Documentation
RTC::PostComponentActionListenerHolder::PostComponentActionListenerHolder ()
Constructor.
virtual RTC::PostComponentActionListenerHolder::~PostComponentActionListenerHolder () [virtual]
Destructor.
Member Function Documentation
void RTC::PostComponentActionListenerHolder::addListener (PostComponentActionListener * listener, bool autoclean)
Add the listener.
This method adds the listener.
Parameters
listener Added listener
autoclean true:The listener is deleted at the destructor., false:The listener is not deleted at the destructor.
void RTC::PostComponentActionListenerHolder::notify (UniqueId ec_id, ReturnCode_t ret)
Notify listeners.
This calls the Callback method of the registered listener.
Parameters
info ConnectorInfo
cdrdata Data
Referenced by RTC::RTObject_impl::postOnAborting(), RTC::RTObject_impl::postOnActivated(), RTC::RTObject_impl::postOnDeactivated(), RTC::RTObject_impl::postOnError(), RTC::RTObject_impl::postOnExecute(), RTC::RTObject_impl::postOnFinalize(), RTC::RTObject_impl::postOnInitialize(), RTC::RTObject_impl::postOnRateChanged(), RTC::RTObject_impl::postOnReset(), RTC::RTObject_impl::postOnShutdown(), RTC::RTObject_impl::postOnStartup(), and RTC::RTObject_impl::postOnStateUpdate().
void RTC::PostComponentActionListenerHolder::removeListener (PostComponentActionListener * listener)
Remove the listener.
This method removes the listener.
Parameters
listener Removed listener