RTC::Manager::Terminator Class Reference
Terminator class.
#include <Manager.h>
Public Member Functions
Terminator (Manager *manager)
Constructor.
void terminate ()
Termination processing.
virtual int open (void *args)
Termination processing activation.
virtual int svc (void)
ORB and manager's termination processing.
Public Attributes
Manager * m_manager
Detailed Description
Terminator class. ORB termination helper class.
Since
0.4.0
Constructor & Destructor Documentation
RTC::Manager::Terminator::Terminator (Manager * manager) [inline]
Constructor.
Constructor
Parameters
manager Manager object
Member Function Documentation
virtual int RTC::Manager::Terminator::open (void * args) [inline, virtual]
Termination processing activation.
Termination processing activation.
Parameters
args Activation argument
Returns
Activation result
Reimplemented from coil::Task .
References coil::Task::activate().
Referenced by terminate().
virtual int RTC::Manager::Terminator::svc (void) [inline, virtual]
ORB and manager's termination processing.
ORB and manager's termination processing.
Returns
Termination result
Reimplemented from coil::Task .
References RTC::Manager::instance(), and RTC::Manager::shutdown().
void RTC::Manager::Terminator::terminate () [inline]
Termination processing.
Start ORB and manager's termination processing.
References open().
Member Data Documentation
Manager* RTC::Manager::Terminator::m_manager