RTC::PeriodicExecutionContext::DFP< Object > Class Template Reference
DFP class.
#include <PeriodicExecutionContext.h>
Public Member Functions
DFP (Object obj, ExecutionContextHandle_t id)
Default constructor.
void on_startup (void)
Function to be invoked when ExecutionContext starts.
void on_shutdown (void)
Function to be invoked when ExecutionContext stops.
void on_activated (const ECStates &st)
Function to be invoked when RT-Component was activated.
void on_deactivated (const ECStates &st)
Function to be invoked when RT-Component was deactivated.
void on_aborting (const ECStates &st)
Function to be invoked when RT-Component occured error.
void on_error (const ECStates &st)
Function to be invoked while RT-Component is in the error state.
void on_reset (const ECStates &st)
Function to be invoked when RT-Component is reset.
void on_execute (const ECStates &st)
Periodic exection function while running RT-Component.
void on_state_update (const ECStates &st)
Function to be invoked periodically while RT-Component executes.
void on_rate_changed (void)
Function to be invoked when the execution cycles of ExecutionContext is changed.
Public Attributes
Object m_obj
The target component to manage.
bool m_active
State flag of the target component to manage.
Detailed Description
template<class Object> class RTC::PeriodicExecutionContext::DFP< Object >
DFP class. Template class to invoke DataFlowParticipant registered in the participant list.
Parameters
Object Type of the target component to manage
Since
0.4.0
Constructor & Destructor Documentation
template<class Object> RTC::PeriodicExecutionContext::DFP< Object >::DFP (Object obj, ExecutionContextHandle_t id) [inline]
Default constructor.
Default constructor
Parameters
obj The target component to manage
id ID of participating ExecutionContext
Member Function Documentation
template<class Object> void RTC::PeriodicExecutionContext::DFP< Object >::on_aborting (const ECStates & st) [inline, virtual]
Function to be invoked when RT-Component occured error.
When the given ExecutionContext transits the Error state, on_aborting of the participation component will be invoked.
Parameters
st The current state of the target RT-Component
Implements RTC::PeriodicExecutionContext::DFPBase .
template<class Object> void RTC::PeriodicExecutionContext::DFP< Object >::on_activated (const ECStates & st) [inline, virtual]
Function to be invoked when RT-Component was activated.
When the given ExecutionContext transits to the Active state, on_activated of the participation component will be invoked. If it fails, the state machine transits to the Errot state.
Parameters
st The current state of the target RT-Component
Implements RTC::PeriodicExecutionContext::DFPBase .
template<class Object> void RTC::PeriodicExecutionContext::DFP< Object >::on_deactivated (const ECStates & st) [inline, virtual]
Function to be invoked when RT-Component was deactivated.
When the given ExecutionContext transits the Deactivate state, on_deactivated of the participation component will be invoked.
Parameters
st The current state of the target RT-Component
Implements RTC::PeriodicExecutionContext::DFPBase .
template<class Object> void RTC::PeriodicExecutionContext::DFP< Object >::on_error (const ECStates & st) [inline, virtual]
Function to be invoked while RT-Component is in the error state.
While the given RT-Component is in the Error state, its on_aborting will be periodically invoked.
Parameters
st The current state of the target RT-Component
Implements RTC::PeriodicExecutionContext::DFPBase .
template<class Object> void RTC::PeriodicExecutionContext::DFP< Object >::on_execute (const ECStates & st) [inline, virtual]
Periodic exection function while running RT-Component.
If the given RT-Component is in the Active state and ExecutionContext is in the Running state, on_execute of the given component will be invoked periodically at the specified execution cycle. If it fails (the return value is other than RTC_OK), its state transits to the Errot state.
Parameters
st The current state of the target RT-Component
Implements RTC::PeriodicExecutionContext::DFPBase .
template<class Object> void RTC::PeriodicExecutionContext::DFP< Object >::on_rate_changed (void) [inline, virtual]
Function to be invoked when the execution cycles of ExecutionContext is changed.
When the execution cycle of the participating ExecutionContext is changed, invoke on_rate_changed of the target component will be invoked.
Implements RTC::PeriodicExecutionContext::DFPBase .
Referenced by RTC::PeriodicExecutionContext::invoke_on_rate_changed::operator()().
template<class Object> void RTC::PeriodicExecutionContext::DFP< Object >::on_reset (const ECStates & st) [inline, virtual]
Function to be invoked when RT-Component is reset.
When the target RT-Component is reset, invoke on_reset of the target component to manage.
Parameters
st The current state of the target RT-Component
Implements RTC::PeriodicExecutionContext::DFPBase .
template<class Object> void RTC::PeriodicExecutionContext::DFP< Object >::on_shutdown (void) [inline, virtual]
Function to be invoked when ExecutionContext stops.
When the given ExecutionContext transits from Running to Stopped, on_shutdown of the participation component will be invoked.
Implements RTC::PeriodicExecutionContext::DFPBase .
Referenced by RTC::PeriodicExecutionContext::invoke_on_shutdown::operator()().
template<class Object> void RTC::PeriodicExecutionContext::DFP< Object >::on_startup (void) [inline, virtual]
Function to be invoked when ExecutionContext starts.
When the given ExecutionContext transits from Stopped to Running, on_startup of the participation component will be invoked.
Implements RTC::PeriodicExecutionContext::DFPBase .
Referenced by RTC::PeriodicExecutionContext::invoke_on_startup::operator()().
template<class Object> void RTC::PeriodicExecutionContext::DFP< Object >::on_state_update (const ECStates & st) [inline, virtual]
Function to be invoked periodically while RT-Component executes.
When the target RT-Component to manage is in the Active state and ExecutionContext is the Running, invoke on_state_update of the target component to manage periodically in specified execution cycle. If it fails (the return value is other than RTC_OK), its state transits to the Errot state.
Parameters
st The current state of the target RT-Component
Implements RTC::PeriodicExecutionContext::DFPBase .
Member Data Documentation
template<class Object> bool RTC::PeriodicExecutionContext::DFP< Object >::m_active
State flag of the target component to manage.
template<class Object> Object RTC::PeriodicExecutionContext::DFP< Object >::m_obj
The target component to manage.
Referenced by RTC::PeriodicExecutionContext::DFP< OpenRTM::DataFlowComponent_var >::on_aborting(), RTC::PeriodicExecutionContext::DFP< OpenRTM::DataFlowComponent_var >::on_activated(), RTC::PeriodicExecutionContext::DFP< OpenRTM::DataFlowComponent_var >::on_deactivated(), RTC::PeriodicExecutionContext::DFP< OpenRTM::DataFlowComponent_var >::on_error(), RTC::PeriodicExecutionContext::DFP< OpenRTM::DataFlowComponent_var >::on_execute(), RTC::PeriodicExecutionContext::DFP< OpenRTM::DataFlowComponent_var >::on_rate_changed(), RTC::PeriodicExecutionContext::DFP< OpenRTM::DataFlowComponent_var >::on_reset(), RTC::PeriodicExecutionContext::DFP< OpenRTM::DataFlowComponent_var >::on_shutdown(), RTC::PeriodicExecutionContext::DFP< OpenRTM::DataFlowComponent_var >::on_startup(), RTC::PeriodicExecutionContext::DFP< OpenRTM::DataFlowComponent_var >::on_state_update(), and RTC::PeriodicExecutionContext::Comp::operator=().