RTC::OutPortConnector Class Reference
OutPortConnector base class.
#include <OutPortConnector.h>
Public Member Functions
DATAPORTSTATUS_ENUM OutPortConnector (ConnectorInfo &info)
Constructor.
virtual ~OutPortConnector ()
Destructor.
const ConnectorInfo & profile ()
Getting Profile.
const char * id ()
Getting Connector ID.
const char * name ()
Getting Connector name.
virtual ReturnCode disconnect ()=0
Disconnect connection.
virtual CdrBufferBase * getBuffer ()=0
Getting Buffer.
virtual ReturnCode write (const cdrMemoryStream &data)=0
Destructor.
virtual void setEndian (const bool endian_type)
Setting an endian type.
virtual bool isLittleEndian ()
return it whether endian setting.
template<class DataType >
ReturnCode write (const DataType &data)
The conversion template of the data type.
Protected Attributes
Logger rtclog
Logger stream.
ConnectorInfo m_profile
PortProfile of the Port.
bool m_littleEndian
Connected Endian.
cdrMemoryStream m_cdr
CDR stream.
Detailed Description
OutPortConnector base class. The base class to derive subclasses for OutPort's Push/Pull Connectors
Since
1.0.0
Constructor & Destructor Documentation
DATAPORTSTATUS_ENUM RTC::OutPortConnector::OutPortConnector (ConnectorInfo & info)
Constructor.
virtual RTC::OutPortConnector::~OutPortConnector () [virtual]
Destructor.
Member Function Documentation
virtual ReturnCode RTC::OutPortConnector::disconnect () [pure virtual]
Disconnect connection.
This operation disconnect this connection
Implements RTC::ConnectorBase .
Implemented in RTC::OutPortPullConnector , and RTC::OutPortPushConnector .
virtual CdrBufferBase* RTC::OutPortConnector::getBuffer () [pure virtual]
Getting Buffer.
This operation returns this connector's buffer
Implements RTC::ConnectorBase .
Implemented in RTC::OutPortPullConnector , and RTC::OutPortPushConnector .
const char* RTC::OutPortConnector::id () [virtual]
Getting Connector ID.
This operation returns Connector ID
Implements RTC::ConnectorBase .
virtual bool RTC::OutPortConnector::isLittleEndian () [virtual]
return it whether endian setting.
Returns
Return true in the case of `little`, false in `big` than it.
Referenced by write().
const char* RTC::OutPortConnector::name () [virtual]
Getting Connector name.
This operation returns Connector name
Implements RTC::ConnectorBase .
const ConnectorInfo& RTC::OutPortConnector::profile () [virtual]
Getting Profile.
This operation returns Connector Profile
Implements RTC::ConnectorBase .
virtual void RTC::OutPortConnector::setEndian (const bool endian_type) [virtual]
Setting an endian type.
This operation set this connector's endian type
template<class DataType > ReturnCode RTC::OutPortConnector::write (const DataType & data) [inline]
The conversion template of the data type.
This is convert it from Timed* into CdrStream.
References isLittleEndian(), m_cdr, RTC_TRACE, and write().
virtual ReturnCode RTC::OutPortConnector::write (const cdrMemoryStream & data) [pure virtual]
Destructor.
The write function to write data from OutPort to Buffer
Implemented in RTC::OutPortPullConnector , and RTC::OutPortPushConnector .
Referenced by write().
Member Data Documentation
cdrMemoryStream RTC::OutPortConnector::m_cdr [protected]
CDR stream.
Referenced by write().
bool RTC::OutPortConnector::m_littleEndian [protected]
Connected Endian.
ConnectorInfo RTC::OutPortConnector::m_profile [protected]
PortProfile of the Port.
Logger RTC::OutPortConnector::rtclog [protected]
Logger stream.