RTC::CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar > Class Template Reference
#include <CorbaConsumer.h>
Public Member Functions
CorbaConsumer ()
Consructor.
CorbaConsumer (const CorbaConsumer &x)
Copy constructor.
CorbaConsumer & operator= (const CorbaConsumer &x)
Assignment operator.
void swap (CorbaConsumer &x)
virtual ~CorbaConsumer (void)
Virtual destructor.
virtual bool setObject (CORBA::Object_ptr obj)
Set Object.
ObjectTypePtr _ptr ()
Get Object reference narrowed as ObjectType.
ObjectTypePtr operator-> ()
Get Object reference narrowed as ObjectType.
virtual void releaseObject ()
Clear CORBA object setting.
Protected Attributes
ObjectTypeVar m_var
CORBA object which has been set.
template<class ObjectType, typename ObjectTypePtr = typename ObjectType::_ptr_type, typename ObjectTypeVar = typename ObjectType::_var_type> class RTC::CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar >
Constructor & Destructor Documentation
template<class ObjectType, typename ObjectTypePtr = typename ObjectType::_ptr_type, typename ObjectTypeVar = typename ObjectType::_var_type> RTC::CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar >::CorbaConsumer () [inline]
Consructor.
template<class ObjectType, typename ObjectTypePtr = typename ObjectType::_ptr_type, typename ObjectTypeVar = typename ObjectType::_var_type> RTC::CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar >::CorbaConsumer (const CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar > & x) [inline]
Copy constructor.
Parameters
x Copy source.
template<class ObjectType, typename ObjectTypePtr = typename ObjectType::_ptr_type, typename ObjectTypeVar = typename ObjectType::_var_type> virtual RTC::CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar >::~CorbaConsumer (void) [inline, virtual]
Virtual destructor.
Member Function Documentation
template<class ObjectType, typename ObjectTypePtr = typename ObjectType::_ptr_type, typename ObjectTypeVar = typename ObjectType::_var_type> ObjectTypePtr RTC::CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar >::_ptr () [inline]
Get Object reference narrowed as ObjectType.
This operation returns object reference narrowed as ObjectType. To use the returned object reference, reference have to be set by setObject(). If object is not set, this operation returns nil object reference.
Returns
The object reference narrowed as ObjectType
template<class ObjectType, typename ObjectTypePtr = typename ObjectType::_ptr_type, typename ObjectTypeVar = typename ObjectType::_var_type> ObjectTypePtr RTC::CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar >::operator-> () [inline]
Get Object reference narrowed as ObjectType.
This operation returns object reference narrowed as ObjectType. To use the returned object reference, reference have to be set by setObject(). If object is not set, this operation returns nil object reference.
Returns
The object reference narrowed as ObjectType
template<class ObjectType, typename ObjectTypePtr = typename ObjectType::_ptr_type, typename ObjectTypeVar = typename ObjectType::_var_type> CorbaConsumer& RTC::CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar >::operator= (const CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar > & x) [inline]
Assignment operator.
Parameters
x Copy source.
Returns
An assignment result
template<class ObjectType, typename ObjectTypePtr = typename ObjectType::_ptr_type, typename ObjectTypeVar = typename ObjectType::_var_type> virtual void RTC::CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar >::releaseObject () [inline, virtual]
Clear CORBA object setting.
Clear CORBA object which is set. Operate nothing for CORBA object itself.
Reimplemented from RTC::CorbaConsumerBase .
Referenced by RTC::CorbaConsumer< ::OpenRTM::OutPortCdr >::releaseObject(), RTC::CorbaConsumer< ::OpenRTM::OutPortCdr >::setObject(), and RTC::CorbaConsumer< ::OpenRTM::OutPortCdr >::~CorbaConsumer().
template<class ObjectType, typename ObjectTypePtr = typename ObjectType::_ptr_type, typename ObjectTypeVar = typename ObjectType::_var_type> virtual bool RTC::CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar >::setObject (CORBA::Object_ptr obj) [inline, virtual]
Set Object.
Override function of ConsumerBase. This operation set an Object to CORBA:Object_var in the class, and this object is narrowed to given template parameter and stored in the member variable.
Parameters
obj CORBA Objecct
Returns
An object setting result. If target object is null, it returns false.
Reimplemented from RTC::CorbaConsumerBase .
template<class ObjectType, typename ObjectTypePtr = typename ObjectType::_ptr_type, typename ObjectTypeVar = typename ObjectType::_var_type> void RTC::CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar >::swap (CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar > & x) [inline]
Referenced by RTC::CorbaConsumer< ::OpenRTM::OutPortCdr >::operator=(), and RTC::CorbaConsumer< ::OpenRTM::OutPortCdr >::swap().
Member Data Documentation
template<class ObjectType, typename ObjectTypePtr = typename ObjectType::_ptr_type, typename ObjectTypeVar = typename ObjectType::_var_type> ObjectTypeVar RTC::CorbaConsumer< ObjectType, ObjectTypePtr, ObjectTypeVar >::m_var [protected]
CORBA object which has been set.
Referenced by RTC::CorbaConsumer< ::OpenRTM::OutPortCdr >::_ptr(), RTC::CorbaConsumer< ::OpenRTM::OutPortCdr >::operator->(), RTC::CorbaConsumer< ::OpenRTM::OutPortCdr >::releaseObject(), RTC::CorbaConsumer< ::OpenRTM::OutPortCdr >::setObject(), and RTC::CorbaConsumer< ::OpenRTM::OutPortCdr >::swap().