RTC::InPortConsumer Class Reference
InPortConsumer abstract class.
#include <InPortConsumer.h>
Classes
struct publishInterfaceProfileFunc
Functor to publish interface profile.
struct subscribeInterfaceFunc
Functor to publish interface profile.
Public Member Functions
virtual DATAPORTSTATUS_ENUM ~InPortConsumer (void)
Destructor.
virtual void init (coil::Properties &prop)=0
Initializing configuration.
virtual ReturnCode put (const cdrMemoryStream &data)=0
Send data to the destination port.
virtual void publishInterfaceProfile (SDOPackage::NVList &properties)=0
Publish InterfaceProfile information.
virtual bool subscribeInterface (const SDOPackage::NVList &properties)=0
Subscribe the data send notification.
virtual void unsubscribeInterface (const SDOPackage::NVList &properties)=0
Unsubscribe the data send notification.
Detailed Description
InPortConsumer abstract class. This is the abstract interface class for the input port Consumer. Concrete classes must implement the following pure virtual functions.
push(): Send data
clone(): Copy ports
subscribeInterface(): Subscribe the data send notification
unsubscribeInterface(): Unsubscribe the data send notification
Since
0.4.0
Constructor & Destructor Documentation
virtual DATAPORTSTATUS_ENUM RTC::InPortConsumer::~InPortConsumer (void) [inline, virtual]
Destructor.
Destructor
Member Function Documentation
virtual void RTC::InPortConsumer::init (coil::Properties & prop) [pure virtual]
Initializing configuration.
This operation would be called to configure this consumer in initialization.
Implemented in RTC::InPortCorbaCdrConsumer .
virtual void RTC::InPortConsumer::publishInterfaceProfile (SDOPackage::NVList & properties) [pure virtual]
Publish InterfaceProfile information.
Publish interfaceProfile information. Check the dataport.interface_type value of the NameValue object specified by an argument in property information and get information only when the interface type of the specified port is matched.
Parameters
properties Properties to get InterfaceProfile information
Implemented in RTC::InPortCorbaCdrConsumer .
Referenced by RTC::InPortConsumer::publishInterfaceProfileFunc::operator()().
virtual ReturnCode RTC::InPortConsumer::put (const cdrMemoryStream & data) [pure virtual]
Send data to the destination port.
Pure virtual function to send data to the destination port.
This function might the following return codes
PORT_OK: Normal return
PORT_ERROR: Error occurred in data transfer process
SEND_FULL: Buffer full although OutPort tried to send data
SEND_TIMEOUT: Timeout although OutPort tried to send data
CONNECTION_LOST: Connection lost
UNKNOWN_ERROR: Unknown error
Implemented in RTC::InPortCorbaCdrConsumer .
virtual bool RTC::InPortConsumer::subscribeInterface (const SDOPackage::NVList & properties) [pure virtual]
Subscribe the data send notification.
Pure virtual function to subscribe the data send notification based on specified property information.
Parameters
properties Properties for reference when subscribing
Returns
Subscription result
Implemented in RTC::InPortCorbaCdrConsumer .
Referenced by RTC::InPortConsumer::subscribeInterfaceFunc::operator()().
virtual void RTC::InPortConsumer::unsubscribeInterface (const SDOPackage::NVList & properties) [pure virtual]
Unsubscribe the data send notification.
Pure virtual function to unsubscribe the data send notification.
Parameters
properties Properties for reference when unsubscribing
Implemented in RTC::InPortCorbaCdrConsumer .