CORBA_Util Namespace Reference
Classes
struct has_nil_helper
has nil helper
struct has_nil_impl
has nil impl: void case
struct has_nil_impl< T, typename has_nil_helper< T,&T::_nil >::type >
has nil impl: valid case
struct has_nil
has nil traits class template
struct is_corba_object
is corba object traits class
class typecode< true, T >
class typecode< false, T >
Functions
template<class T >
const char * toTypename ()
Getting CORBA defined type as characters.
template<class T >
const char * toTypenameOfStruct ()
template<class T >
const char * toTypenameOfObject ()
template<class T >
const char * toRepositoryId ()
Getting CORBA defined type as characters.
template<class T >
const char * toRepositoryIdOfStruct ()
template<class T >
const char * toRepositoryIdOfObject ()
Function Documentation
template<class T > const char* CORBA_Util::toRepositoryId () [inline]
Getting CORBA defined type as characters.
This function returns the type name if class or struct type that is defined CORBA IDL. The template parameter can be a type which has type code.
 std::cout << toRepositoryId<RTC::TimedFloat>() << std::endl;
 std::cout << toRepositoryId<RTC::RTObject>() << std::endl;
 gives the following results.
 IDL:RTC/TimedFloat:1.0
 IDL:omg.org/RTC/RTObject:1.0
template<class T > const char* CORBA_Util::toRepositoryIdOfObject () [inline]
References CORBA_Util::typecode< true, T >::id().
template<class T > const char* CORBA_Util::toRepositoryIdOfStruct () [inline]
References CORBA_Util::typecode< false, T >::id().
template<class T > const char* CORBA_Util::toTypename () [inline]
Getting CORBA defined type as characters.
This function returns the type name if class or struct type that is defined CORBA IDL. The template parameter can be a type which has type code.
 std::cout << toTypename<RTC::TimedFloat>() << std::endl;
 std::cout << toTypename<RTC::RTObject>() << std::endl;
 gives the following results.
 TimedFloat
 RTObject
template<class T > const char* CORBA_Util::toTypenameOfObject () [inline]
References CORBA_Util::typecode< true, T >::name().
template<class T > const char* CORBA_Util::toTypenameOfStruct () [inline]
References CORBA_Util::typecode< false, T >::name().