OutPort.h File Reference
OutPort class.
#include <iostream>
#include <string>
#include <coil/TimeValue.h>
#include <coil/Time.h>
#include <coil/TimeMeasure.h>
#include <coil/OS.h>
#include <rtm/RTC.h>
#include <rtm/Typename.h>
#include <rtm/OutPortBase.h>
#include <rtm/CdrBufferBase.h>
#include <rtm/PortCallback.h>
#include <rtm/OutPortConnector.h>
Classes
class RTC::OutPort< DataType >
OutPort template class.
Namespaces
namespace RTC
RT-Component.
Functions
template<class DataType >
void setTimestamp (DataType &data)
Setting timestamp to data.
Detailed Description
OutPort class.
Date
Date
2007-12-31 03:08:05
Author
Noriaki Ando <n-ando@aist.go.jp>
Copyright (C) 2006-2009 Noriaki Ando Task-intelligence Research Group, Intelligent Systems Research Institute, National Institute of Advanced Industrial Science and Technology (AIST), Japan All rights reserved.
Id
OutPort.h 2143 2011-05-26 14:30:49Z n-ando
Function Documentation
template<class DataType > void setTimestamp (DataType & data) [inline]
Setting timestamp to data.
This function sets timestamp to data of data port. This data should have tm.sec, tm.nsec as members of the structure.
Parameters
data Data to be set timestamp. After executing this function, current timestamp is set to the data.
References coil::gettimeofday(), coil::TimeValue::sec(), and coil::TimeValue::usec().