.TH COIL 1

.SH NAME

coil-config \- get information about installed coil library

.SH SYNOPSIS

.B coil-config [OPTIONS]

.SH DESCRIPTION

Provices information about coil library.

.SH OPTIONS

.TP 5
\-\-prefix
Show coil installation prefix.
.TP 5
\-\-exe-prefix
Show coil exec prefix.
.TP 5
\-\-version
Output Coil information.
.TP 5
\-\-libs
Print library linking information.
.TP 5
\-\-cflags
Print pre-processor and compiler flags.
.TP 5
\-\-libdir
Print library installation directory.

.SH AUTHOR

Noriaki Ando <n-ando@aist.go.jp>
