Document: openrtm-aist-idl
Title: OpenRTM IDL reference
Author: Noriaki Ando <n-ando@aist.go.jp>
Abstract: Describes OpenRTM IDL interfaces.
Section: Science
Format: HTML
Index: /usr/share/openrtm-1.1/doc/IDLReference-en/html/index.html
Files: /usr/share/openrtm-1.1/doc/IDLReference-en/html/*.html
