.TH OPENRTM 1

.SH NAME

rtm-config \- get information about installed OpenRTM software.

.SH SYNOPSIS

.B rtm-config [OPTIONS]

.SH DESCRIPTION

Provide information about installed OpenRTM software.

.SH OPTIONS

.TP 5
\-\-prefix
.TP 5
\-\-exec-prefix
.TP 5
\-\-data-prefix
.TP 5
\-\-version
.TP 5
\-\-cxx
.TP 5
\-\-cflags
.TP 5
\-\-cflags-only-I
.TP 5
\-\-cflags-only-other
.TP 5
\-\-libs
.TP 5
\-\-libs-only-l
.TP 5
\-\-libs-only-L
.TP 5
\-\-libs-only-other
.TP 5
\-\-libdir
.TP 5
\-\-orb
.TP 5
\-\-idlc
.TP 5
\-\-idlflags
.TP 5
\-\-idlflags-only-I
.TP 5
\-\-idlflags-only-other

.TP 5
\-\-rtm-includedir
.TP 5
\-\-rtm-idldir
.TP 5
\-\-rtm-libdir
.TP 5
\-\-rtm-datadir
.TP 5
\-\-rtm-rtcdir
.TP 5
\-\-rtm-ecdir
.TP 5
\-\-rtm-rtmdir
.TP 5
\-\-rtm-svcdir
.TP 5
\-\-rtm-docdir
.TP 5
\-\-rtm-exampledir
.TP 5
\-\-coil-includedir

.SH SEE ALSO

.TP
.B Home Page
http://openrtm.org/

.SH AUTHOR

2003-2012, Noriaki Ando and the OpenRTM-aist Project team
